//------------------------------------------------
//admjohn_c.c
//------------------------------------------------
// admjohn - Version 1.0
// Created By: Martinus with the Quake ToolKit (www.planetquake.com/eoc)
//             -
// -
//
// Admiral John (NOT John Carmack)
// Full name : John Kaleb Admiral
// He was the leader of the mothership 
// called UAC-Curiosity III. to discover 
// the planet called Nibiru.
//------------------------------------------------

#include "chars.h"

skill 1
{
CHARACTERISTIC_NAME                            "admjohn"
CHARACTERISTIC_GENDER                          "Male"
CHARACTERISTIC_ATTACK_SKILL                    0.25
CHARACTERISTIC_WEAPONWEIGHTS                   "bots/admjohn_w.c"
CHARACTERISTIC_AIM_SKILL                       0.3
CHARACTERISTIC_AIM_ACCURACY                    0.2
CHARACTERISTIC_VIEW_FACTOR                     0.14
CHARACTERISTIC_VIEW_MAXCHANGE                  73
CHARACTERISTIC_REACTIONTIME                    0.25

CHARACTERISTIC_CHAT_FILE                       "bots/admjohn_t.c"
CHARACTERISTIC_CHAT_NAME                       "admjohn"
CHARACTERISTIC_CHAT_CPM                        88
CHARACTERISTIC_CHAT_INSULT                     0.62
CHARACTERISTIC_CHAT_MISC                       0.2
CHARACTERISTIC_CHAT_STARTENDLEVEL              0.39
CHARACTERISTIC_CHAT_ENTEREXITGAME              0.35
CHARACTERISTIC_CHAT_KILL                       0.36
CHARACTERISTIC_CHAT_DEATH                      0.39
CHARACTERISTIC_CHAT_ENEMYSUICIDE               0.36
CHARACTERISTIC_CHAT_HITTALKING                 0.39
CHARACTERISTIC_CHAT_HITNODEATH                 0.39
CHARACTERISTIC_CHAT_HITNOKILL                  0.39
CHARACTERISTIC_CHAT_RANDOM                     0.2
CHARACTERISTIC_CHAT_REPLY                      0.45

CHARACTERISTIC_CROUCHER                        0.15
CHARACTERISTIC_JUMPER                          0.73
CHARACTERISTIC_WEAPONJUMPING                   0.47
CHARACTERISTIC_GRAPPLE_USER                    0
CHARACTERISTIC_WALKER                          0

CHARACTERISTIC_ITEMWEIGHTS                     "bots/admjohn_i.c"
CHARACTERISTIC_AGGRESSION                      1
CHARACTERISTIC_SELFPRESERVATION                0.4
CHARACTERISTIC_VENGEFULNESS                    0.46
CHARACTERISTIC_CAMPER                          0

CHARACTERISTIC_EASY_FRAGGER                    0.63
CHARACTERISTIC_ALERTNESS                       0.25

CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN         0.08
CHARACTERISTIC_AIM_ACCURACY_SHOTGUN            0.18
CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER     0.33
CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER    0.25
CHARACTERISTIC_AIM_ACCURACY_LIGHTNING          0.55
CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN          0.17
CHARACTERISTIC_AIM_ACCURACY_RAILGUN            0.27
CHARACTERISTIC_AIM_ACCURACY_BFG10K             0.16
CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER        0.27
CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER       0.25
CHARACTERISTIC_AIM_SKILL_PLASMAGUN             0.17
CHARACTERISTIC_AIM_SKILL_BFG10K                0.21

CHARACTERISTIC_FIRETHROTTLE                    0.6
}

skill 4
{
CHARACTERISTIC_NAME                            "admjohn"
CHARACTERISTIC_GENDER                          "Male"
CHARACTERISTIC_ATTACK_SKILL                    0.52
CHARACTERISTIC_WEAPONWEIGHTS                   "bots/admjohn_w.c"
CHARACTERISTIC_AIM_SKILL                       0.57
CHARACTERISTIC_AIM_ACCURACY                    0.39
CHARACTERISTIC_VIEW_FACTOR                     0.56
CHARACTERISTIC_VIEW_MAXCHANGE                  158
CHARACTERISTIC_REACTIONTIME                    3.11

CHARACTERISTIC_CHAT_FILE                       "bots/admjohn_t.c"
CHARACTERISTIC_CHAT_NAME                       "admjohn"
CHARACTERISTIC_CHAT_CPM                        88
CHARACTERISTIC_CHAT_INSULT                     0.62
CHARACTERISTIC_CHAT_MISC                       0.2
CHARACTERISTIC_CHAT_STARTENDLEVEL              0.39
CHARACTERISTIC_CHAT_ENTEREXITGAME              0.35
CHARACTERISTIC_CHAT_KILL                       0.36
CHARACTERISTIC_CHAT_DEATH                      0.39
CHARACTERISTIC_CHAT_ENEMYSUICIDE               0.36
CHARACTERISTIC_CHAT_HITTALKING                 0.39
CHARACTERISTIC_CHAT_HITNODEATH                 0.39
CHARACTERISTIC_CHAT_HITNOKILL                  0.39
CHARACTERISTIC_CHAT_RANDOM                     0.2
CHARACTERISTIC_CHAT_REPLY                      0.45

CHARACTERISTIC_CROUCHER                        0.15
CHARACTERISTIC_JUMPER                          0.73
CHARACTERISTIC_WEAPONJUMPING                   0.47
CHARACTERISTIC_GRAPPLE_USER                    0
CHARACTERISTIC_WALKER                          0

CHARACTERISTIC_ITEMWEIGHTS                     "bots/admjohn_i.c"
CHARACTERISTIC_AGGRESSION                      1
CHARACTERISTIC_SELFPRESERVATION                0.53
CHARACTERISTIC_VENGEFULNESS                    0.46
CHARACTERISTIC_CAMPER                          0.47

CHARACTERISTIC_EASY_FRAGGER                    0.64
CHARACTERISTIC_ALERTNESS                       0.61

CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN         0.68
CHARACTERISTIC_AIM_ACCURACY_SHOTGUN            0.71
CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER     0.56
CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER    0.25
CHARACTERISTIC_AIM_ACCURACY_LIGHTNING          0.55
CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN          0.41
CHARACTERISTIC_AIM_ACCURACY_RAILGUN            0.74
CHARACTERISTIC_AIM_ACCURACY_BFG10K             0.29
CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER        0.36
CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER       0.48
CHARACTERISTIC_AIM_SKILL_PLASMAGUN             0.57
CHARACTERISTIC_AIM_SKILL_BFG10K                0.46

CHARACTERISTIC_FIRETHROTTLE                    0.75
}

skill 5
{
CHARACTERISTIC_NAME                            "admjohn"
CHARACTERISTIC_GENDER                          "Male"
CHARACTERISTIC_ATTACK_SKILL                    0.83
CHARACTERISTIC_WEAPONWEIGHTS                   "bots/admjohn_w.c"
CHARACTERISTIC_AIM_SKILL                       0.72
CHARACTERISTIC_AIM_ACCURACY                    0.77
CHARACTERISTIC_VIEW_FACTOR                     0.91
CHARACTERISTIC_VIEW_MAXCHANGE                  253
CHARACTERISTIC_REACTIONTIME                    4.25

CHARACTERISTIC_CHAT_FILE                       "bots/admjohn_t.c"
CHARACTERISTIC_CHAT_NAME                       "admjohn"
CHARACTERISTIC_CHAT_CPM                        88
CHARACTERISTIC_CHAT_INSULT                     0.62
CHARACTERISTIC_CHAT_MISC                       0.2
CHARACTERISTIC_CHAT_STARTENDLEVEL              0.39
CHARACTERISTIC_CHAT_ENTEREXITGAME              0.35
CHARACTERISTIC_CHAT_KILL                       0.36
CHARACTERISTIC_CHAT_DEATH                      0.39
CHARACTERISTIC_CHAT_ENEMYSUICIDE               0.36
CHARACTERISTIC_CHAT_HITTALKING                 0.39
CHARACTERISTIC_CHAT_HITNODEATH                 0.39
CHARACTERISTIC_CHAT_HITNOKILL                  0.39
CHARACTERISTIC_CHAT_RANDOM                     0.2
CHARACTERISTIC_CHAT_REPLY                      0.45

CHARACTERISTIC_CROUCHER                        0.15
CHARACTERISTIC_JUMPER                          0.73
CHARACTERISTIC_WEAPONJUMPING                   0.47
CHARACTERISTIC_GRAPPLE_USER                    0
CHARACTERISTIC_WALKER                          0

CHARACTERISTIC_ITEMWEIGHTS                     "bots/admjohn_i.c"
CHARACTERISTIC_AGGRESSION                      1
CHARACTERISTIC_SELFPRESERVATION                0.53
CHARACTERISTIC_VENGEFULNESS                    0.46
CHARACTERISTIC_CAMPER                          0.47

CHARACTERISTIC_EASY_FRAGGER                    0.64
CHARACTERISTIC_ALERTNESS                       0.82

CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN         0.68
CHARACTERISTIC_AIM_ACCURACY_SHOTGUN            0.71
CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER     0.56
CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER    0.25
CHARACTERISTIC_AIM_ACCURACY_LIGHTNING          0.55
CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN          0.79
CHARACTERISTIC_AIM_ACCURACY_RAILGUN            0.74
CHARACTERISTIC_AIM_ACCURACY_BFG10K             0.49
CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER        0.51
CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER       0.48
CHARACTERISTIC_AIM_SKILL_PLASMAGUN             0.57
CHARACTERISTIC_AIM_SKILL_BFG10K                0.46

CHARACTERISTIC_FIRETHROTTLE                    0.75
}
