//===========================================================================
// Name:			bryson_c.c
// Function:		Bryson, Lun3DM3 Bot
// "Programmer":	Lunaran
//===========================================================================

#include "chars.h"

skill 1
{
	CHARACTERISTIC_NAME							"Bryson"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.85
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/bryson_w.c"
	CHARACTERISTIC_AIM_SKILL					0.7
	CHARACTERISTIC_AIM_ACCURACY					0.7
	CHARACTERISTIC_VIEW_FACTOR					1.0
	CHARACTERISTIC_VIEW_MAXCHANGE				180
	CHARACTERISTIC_REACTIONTIME					1.5

	CHARACTERISTIC_CHAT_FILE					"bots/bryson_t.c"
	CHARACTERISTIC_CHAT_NAME					"Bryson"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.0
	CHARACTERISTIC_CHAT_MISC					0.0
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.0
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.0
	CHARACTERISTIC_CHAT_KILL					0.0
	CHARACTERISTIC_CHAT_DEATH					0.0
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.0
	CHARACTERISTIC_CHAT_HITTALKING				0.0
	CHARACTERISTIC_CHAT_HITNODEATH				0.0
	CHARACTERISTIC_CHAT_HITNOKILL				0.0
	CHARACTERISTIC_CHAT_RANDOM					0.0
	CHARACTERISTIC_CHAT_REPLY					0.0

	CHARACTERISTIC_CROUCHER						0.3
	CHARACTERISTIC_JUMPER						0.3
	CHARACTERISTIC_WEAPONJUMPING				0.5
	CHARACTERISTIC_GRAPPLE_USER					0.3

	CHARACTERISTIC_ITEMWEIGHTS					"bots/bryson_i.c"
	CHARACTERISTIC_AGGRESSION					0.4
	CHARACTERISTIC_SELFPRESERVATION				0.8
	CHARACTERISTIC_VENGEFULNESS					0.3
	CHARACTERISTIC_CAMPER						0.2

	CHARACTERISTIC_EASY_FRAGGER					0.2
	CHARACTERISTIC_ALERTNESS					0.8

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.7
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.6
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.7
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.7
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		0.7
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.6
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.5
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.6
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.8
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.8
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.7
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.7

	CHARACTERISTIC_FIRETHROTTLE					0.45
}

skill 4
{
	CHARACTERISTIC_NAME							"Bryson"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.85
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/bryson_w.c"
	CHARACTERISTIC_AIM_SKILL					0.8
	CHARACTERISTIC_AIM_ACCURACY					0.8
	CHARACTERISTIC_VIEW_FACTOR					1.0
	CHARACTERISTIC_VIEW_MAXCHANGE				270
	CHARACTERISTIC_REACTIONTIME					0.5

	CHARACTERISTIC_CHAT_FILE					"bots/bryson_t.c"
	CHARACTERISTIC_CHAT_NAME					"Bryson"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.0
	CHARACTERISTIC_CHAT_MISC					0.0
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.0
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.0
	CHARACTERISTIC_CHAT_KILL					0.0
	CHARACTERISTIC_CHAT_DEATH					0.0
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.0
	CHARACTERISTIC_CHAT_HITTALKING				0.0
	CHARACTERISTIC_CHAT_HITNODEATH				0.0
	CHARACTERISTIC_CHAT_HITNOKILL				0.0
	CHARACTERISTIC_CHAT_RANDOM					0.0
	CHARACTERISTIC_CHAT_REPLY					0.0

	CHARACTERISTIC_CROUCHER						0.3
	CHARACTERISTIC_JUMPER						0.4
	CHARACTERISTIC_WEAPONJUMPING				0.6
	CHARACTERISTIC_GRAPPLE_USER					0.3

	CHARACTERISTIC_ITEMWEIGHTS					"bots/bryson_i.c"
	CHARACTERISTIC_AGGRESSION					0.5
	CHARACTERISTIC_SELFPRESERVATION				0.9
	CHARACTERISTIC_VENGEFULNESS					0.2
	CHARACTERISTIC_CAMPER						0.1

	CHARACTERISTIC_EASY_FRAGGER					0.15
	CHARACTERISTIC_ALERTNESS					0.85

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.7
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.7
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.8
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.8
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		0.8
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.7
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.6
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.7
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.9
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.9
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.8
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.8

	CHARACTERISTIC_FIRETHROTTLE					0.35
}

skill 5
{
	CHARACTERISTIC_NAME							"Bryson"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.89
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/bryson_w.c"
	CHARACTERISTIC_AIM_SKILL					0.8
	CHARACTERISTIC_AIM_ACCURACY					0.8
	CHARACTERISTIC_VIEW_FACTOR					1.0
	CHARACTERISTIC_VIEW_MAXCHANGE				270
	CHARACTERISTIC_REACTIONTIME					0.25

	CHARACTERISTIC_CHAT_FILE					"bots/doobryson_t.c"
	CHARACTERISTIC_CHAT_NAME					"Bryson"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.0
	CHARACTERISTIC_CHAT_MISC					0.0
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.0
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.0
	CHARACTERISTIC_CHAT_KILL					0.0
	CHARACTERISTIC_CHAT_DEATH					0.0
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.0
	CHARACTERISTIC_CHAT_HITTALKING				0.0
	CHARACTERISTIC_CHAT_HITNODEATH				0.0
	CHARACTERISTIC_CHAT_HITNOKILL				0.0
	CHARACTERISTIC_CHAT_RANDOM					0.0
	CHARACTERISTIC_CHAT_REPLY					0.0

	CHARACTERISTIC_CROUCHER						0.3
	CHARACTERISTIC_JUMPER						0.4
	CHARACTERISTIC_WEAPONJUMPING				0.7
	CHARACTERISTIC_GRAPPLE_USER					0.3

	CHARACTERISTIC_ITEMWEIGHTS					"bots/bryson_i.c"
	CHARACTERISTIC_AGGRESSION					0.6
	CHARACTERISTIC_SELFPRESERVATION				0.9
	CHARACTERISTIC_VENGEFULNESS					0.1
	CHARACTERISTIC_CAMPER						0.1

	CHARACTERISTIC_EASY_FRAGGER					0.1
	CHARACTERISTIC_ALERTNESS					0.9

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.75
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.75
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.85
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.85
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		0.85
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.75
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.65
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.75
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.95
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.95
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.85
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.85

	CHARACTERISTIC_FIRETHROTTLE					0.3
}