//------------------------------------------------
//coljanella_c.c
//------------------------------------------------
// coljanella - Version 1.0
// Created By: Martinus with the Quake ToolKit (www.planetquake.com/eoc)
//             -
// -
//
// Colonel Janella
// Full name : Colonel Janella Sabando 
// (her name is form the Doom Bible. I 
// don't know much about her...)
// She was a military leader, who 
// supervised the Nibiru action.
// 
// (She is not so talkative...)
//------------------------------------------------

#include "chars.h"

skill 1
{
CHARACTERISTIC_NAME                            "coljanella"
CHARACTERISTIC_GENDER                          "Female"
CHARACTERISTIC_ATTACK_SKILL                    0.48
CHARACTERISTIC_WEAPONWEIGHTS                   "bots/coljanella_w.c"
CHARACTERISTIC_AIM_SKILL                       0.51
CHARACTERISTIC_AIM_ACCURACY                    0.46
CHARACTERISTIC_VIEW_FACTOR                     0.15
CHARACTERISTIC_VIEW_MAXCHANGE                  130
CHARACTERISTIC_REACTIONTIME                    1.4

CHARACTERISTIC_CHAT_FILE                       "bots/coljanella_t.c"
CHARACTERISTIC_CHAT_NAME                       "coljanella"
CHARACTERISTIC_CHAT_CPM                        25
CHARACTERISTIC_CHAT_INSULT                     0
CHARACTERISTIC_CHAT_MISC                       0.54
CHARACTERISTIC_CHAT_STARTENDLEVEL              0.05
CHARACTERISTIC_CHAT_ENTEREXITGAME              0.03
CHARACTERISTIC_CHAT_KILL                       0
CHARACTERISTIC_CHAT_DEATH                      0
CHARACTERISTIC_CHAT_ENEMYSUICIDE               0
CHARACTERISTIC_CHAT_HITTALKING                 0
CHARACTERISTIC_CHAT_HITNODEATH                 0
CHARACTERISTIC_CHAT_HITNOKILL                  0.11
CHARACTERISTIC_CHAT_RANDOM                     0.6
CHARACTERISTIC_CHAT_REPLY                      0

CHARACTERISTIC_CROUCHER                        0.25
CHARACTERISTIC_JUMPER                          0.18
CHARACTERISTIC_WEAPONJUMPING                   0.18
CHARACTERISTIC_GRAPPLE_USER                    0
CHARACTERISTIC_WALKER                          0.14

CHARACTERISTIC_ITEMWEIGHTS                     "bots/coljanella_i.c"
CHARACTERISTIC_AGGRESSION                      0.11
CHARACTERISTIC_SELFPRESERVATION                0.16
CHARACTERISTIC_VENGEFULNESS                    0.11
CHARACTERISTIC_CAMPER                          0.1

CHARACTERISTIC_EASY_FRAGGER                    0.1
CHARACTERISTIC_ALERTNESS                       0.19

CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN         0.32
CHARACTERISTIC_AIM_ACCURACY_SHOTGUN            0.11
CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER     0.16
CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER    0.05
CHARACTERISTIC_AIM_ACCURACY_LIGHTNING          0.38
CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN          0.15
CHARACTERISTIC_AIM_ACCURACY_RAILGUN            0.31
CHARACTERISTIC_AIM_ACCURACY_BFG10K             0.24
CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER        0.09
CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER       0.17
CHARACTERISTIC_AIM_SKILL_PLASMAGUN             0.27
CHARACTERISTIC_AIM_SKILL_BFG10K                0.11

CHARACTERISTIC_FIRETHROTTLE                    0.11
}

skill 4
{
CHARACTERISTIC_NAME                            "coljanella"
CHARACTERISTIC_GENDER                          "Female"
CHARACTERISTIC_ATTACK_SKILL                    0.78
CHARACTERISTIC_WEAPONWEIGHTS                   "bots/coljanella_w.c"
CHARACTERISTIC_AIM_SKILL                       0.77
CHARACTERISTIC_AIM_ACCURACY                    0.77
CHARACTERISTIC_VIEW_FACTOR                     0.24
CHARACTERISTIC_VIEW_MAXCHANGE                  265
CHARACTERISTIC_REACTIONTIME                    3.55

CHARACTERISTIC_CHAT_FILE                       "bots/coljanella_t.c"
CHARACTERISTIC_CHAT_NAME                       "coljanella"
CHARACTERISTIC_CHAT_CPM                        25
CHARACTERISTIC_CHAT_INSULT                     0
CHARACTERISTIC_CHAT_MISC                       0.54
CHARACTERISTIC_CHAT_STARTENDLEVEL              0.05
CHARACTERISTIC_CHAT_ENTEREXITGAME              0.03
CHARACTERISTIC_CHAT_KILL                       0
CHARACTERISTIC_CHAT_DEATH                      0
CHARACTERISTIC_CHAT_ENEMYSUICIDE               0
CHARACTERISTIC_CHAT_HITTALKING                 0
CHARACTERISTIC_CHAT_HITNODEATH                 0
CHARACTERISTIC_CHAT_HITNOKILL                  0.11
CHARACTERISTIC_CHAT_RANDOM                     0.6
CHARACTERISTIC_CHAT_REPLY                      0

CHARACTERISTIC_CROUCHER                        0.47
CHARACTERISTIC_JUMPER                          0.8
CHARACTERISTIC_WEAPONJUMPING                   0.18
CHARACTERISTIC_GRAPPLE_USER                    0
CHARACTERISTIC_WALKER                          0.14

CHARACTERISTIC_ITEMWEIGHTS                     "bots/coljanella_i.c"
CHARACTERISTIC_AGGRESSION                      0.24
CHARACTERISTIC_SELFPRESERVATION                0.34
CHARACTERISTIC_VENGEFULNESS                    0.25
CHARACTERISTIC_CAMPER                          0.22

CHARACTERISTIC_EASY_FRAGGER                    0.2
CHARACTERISTIC_ALERTNESS                       0.82

CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN         0.68
CHARACTERISTIC_AIM_ACCURACY_SHOTGUN            0.25
CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER     0.43
CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER    0.14
CHARACTERISTIC_AIM_ACCURACY_LIGHTNING          0.7
CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN          0.62
CHARACTERISTIC_AIM_ACCURACY_RAILGUN            0.85
CHARACTERISTIC_AIM_ACCURACY_BFG10K             0.54
CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER        0.22
CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER       0.37
CHARACTERISTIC_AIM_SKILL_PLASMAGUN             0.45
CHARACTERISTIC_AIM_SKILL_BFG10K                0.25

CHARACTERISTIC_FIRETHROTTLE                    0.25
}

skill 5
{
CHARACTERISTIC_NAME                            "coljanella"
CHARACTERISTIC_GENDER                          "Female"
CHARACTERISTIC_ATTACK_SKILL                    0.78
CHARACTERISTIC_WEAPONWEIGHTS                   "bots/coljanella_w.c"
CHARACTERISTIC_AIM_SKILL                       0.77
CHARACTERISTIC_AIM_ACCURACY                    0.77
CHARACTERISTIC_VIEW_FACTOR                     0.24
CHARACTERISTIC_VIEW_MAXCHANGE                  265
CHARACTERISTIC_REACTIONTIME                    3.55

CHARACTERISTIC_CHAT_FILE                       "bots/coljanella_t.c"
CHARACTERISTIC_CHAT_NAME                       "coljanella"
CHARACTERISTIC_CHAT_CPM                        25
CHARACTERISTIC_CHAT_INSULT                     0
CHARACTERISTIC_CHAT_MISC                       0.54
CHARACTERISTIC_CHAT_STARTENDLEVEL              0.05
CHARACTERISTIC_CHAT_ENTEREXITGAME              0.03
CHARACTERISTIC_CHAT_KILL                       0
CHARACTERISTIC_CHAT_DEATH                      0
CHARACTERISTIC_CHAT_ENEMYSUICIDE               0
CHARACTERISTIC_CHAT_HITTALKING                 0
CHARACTERISTIC_CHAT_HITNODEATH                 0
CHARACTERISTIC_CHAT_HITNOKILL                  0.11
CHARACTERISTIC_CHAT_RANDOM                     0.6
CHARACTERISTIC_CHAT_REPLY                      0

CHARACTERISTIC_CROUCHER                        0.63
CHARACTERISTIC_JUMPER                          0.8
CHARACTERISTIC_WEAPONJUMPING                   0.18
CHARACTERISTIC_GRAPPLE_USER                    0
CHARACTERISTIC_WALKER                          0.14

CHARACTERISTIC_ITEMWEIGHTS                     "bots/coljanella_i.c"
CHARACTERISTIC_AGGRESSION                      0.24
CHARACTERISTIC_SELFPRESERVATION                0.34
CHARACTERISTIC_VENGEFULNESS                    0.25
CHARACTERISTIC_CAMPER                          0.22

CHARACTERISTIC_EASY_FRAGGER                    0.3
CHARACTERISTIC_ALERTNESS                       0.82

CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN         0.68
CHARACTERISTIC_AIM_ACCURACY_SHOTGUN            0.25
CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER     0.43
CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER    0.14
CHARACTERISTIC_AIM_ACCURACY_LIGHTNING          0.7
CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN          0.62
CHARACTERISTIC_AIM_ACCURACY_RAILGUN            0.85
CHARACTERISTIC_AIM_ACCURACY_BFG10K             0.54
CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER        0.22
CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER       0.37
CHARACTERISTIC_AIM_SKILL_PLASMAGUN             0.45
CHARACTERISTIC_AIM_SKILL_BFG10K                0.25

CHARACTERISTIC_FIRETHROTTLE                    0.25
}
