//===========================================================================
// Name:			mccormick_c.c
// Function:		McCormick, Lun3DM3 Bot
// "Programmer":	Lunaran
//===========================================================================

#include "chars.h"

skill 1
{
	CHARACTERISTIC_NAME							"McCormick"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.4
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/mccormick_w.c"
	CHARACTERISTIC_AIM_SKILL					0.4
	CHARACTERISTIC_AIM_ACCURACY					0.4
	CHARACTERISTIC_VIEW_FACTOR					1.0
	CHARACTERISTIC_VIEW_MAXCHANGE				180
	CHARACTERISTIC_REACTIONTIME					3.0

	CHARACTERISTIC_CHAT_FILE					"bots/mccormick_t.c"
	CHARACTERISTIC_CHAT_NAME					"McCormick"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.0
	CHARACTERISTIC_CHAT_MISC					0.0
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.0
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.0
	CHARACTERISTIC_CHAT_KILL					0.0
	CHARACTERISTIC_CHAT_DEATH					0.0
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.0
	CHARACTERISTIC_CHAT_HITTALKING				0.0
	CHARACTERISTIC_CHAT_HITNODEATH				0.0
	CHARACTERISTIC_CHAT_HITNOKILL				0.0
	CHARACTERISTIC_CHAT_RANDOM					0.0
	CHARACTERISTIC_CHAT_REPLY					0.0

	CHARACTERISTIC_CROUCHER						0.0
	CHARACTERISTIC_JUMPER						1.0
	CHARACTERISTIC_WEAPONJUMPING				0.8
	CHARACTERISTIC_GRAPPLE_USER					0.4

	CHARACTERISTIC_ITEMWEIGHTS					"bots/mccormick_i.c"
	CHARACTERISTIC_AGGRESSION					0.8
	CHARACTERISTIC_SELFPRESERVATION				0.3
	CHARACTERISTIC_VENGEFULNESS					0.7
	CHARACTERISTIC_CAMPER						0.3

	CHARACTERISTIC_EASY_FRAGGER					0.8
	CHARACTERISTIC_ALERTNESS					0.6

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.7
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.7
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.6
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.4
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		0.5
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.5
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.5
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.5
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.4
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.3
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.6
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.2

	CHARACTERISTIC_FIRETHROTTLE					0.75
}

skill 4
{
	CHARACTERISTIC_NAME							"McCormick"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.5
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/mccormick_w.c"
	CHARACTERISTIC_AIM_SKILL					0.5
	CHARACTERISTIC_AIM_ACCURACY					0.5
	CHARACTERISTIC_VIEW_FACTOR					1.0
	CHARACTERISTIC_VIEW_MAXCHANGE				180
	CHARACTERISTIC_REACTIONTIME					2.0

	CHARACTERISTIC_CHAT_FILE					"bots/mccormick_t.c"
	CHARACTERISTIC_CHAT_NAME					"McCormick"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.0
	CHARACTERISTIC_CHAT_MISC					0.0
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.0
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.0
	CHARACTERISTIC_CHAT_KILL					0.0
	CHARACTERISTIC_CHAT_DEATH					0.0
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.0
	CHARACTERISTIC_CHAT_HITTALKING				0.0
	CHARACTERISTIC_CHAT_HITNODEATH				0.0
	CHARACTERISTIC_CHAT_HITNOKILL				0.0
	CHARACTERISTIC_CHAT_RANDOM					0.0
	CHARACTERISTIC_CHAT_REPLY					0.0

	CHARACTERISTIC_CROUCHER						0.0
	CHARACTERISTIC_JUMPER						1.0
	CHARACTERISTIC_WEAPONJUMPING				0.7
	CHARACTERISTIC_GRAPPLE_USER					0.3

	CHARACTERISTIC_ITEMWEIGHTS					"bots/mccormick_i.c"
	CHARACTERISTIC_AGGRESSION					0.8
	CHARACTERISTIC_SELFPRESERVATION				0.1
	CHARACTERISTIC_VENGEFULNESS					0.8
	CHARACTERISTIC_CAMPER						0.2

	CHARACTERISTIC_EASY_FRAGGER					0.8
	CHARACTERISTIC_ALERTNESS					0.7

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.75
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.85
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.65
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.55
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		0.55
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.65
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.55
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.55
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.45
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.35
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.75
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.25

	CHARACTERISTIC_FIRETHROTTLE					0.8
}

skill 5
{
	CHARACTERISTIC_NAME							"McCormick"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.6
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/mccormick_w.c"
	CHARACTERISTIC_AIM_SKILL					0.6
	CHARACTERISTIC_AIM_ACCURACY					0.6
	CHARACTERISTIC_VIEW_FACTOR					1.0
	CHARACTERISTIC_VIEW_MAXCHANGE				240
	CHARACTERISTIC_REACTIONTIME					1.0

	CHARACTERISTIC_CHAT_FILE					"bots/mccormick_t.c"
	CHARACTERISTIC_CHAT_NAME					"McCormick"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.0
	CHARACTERISTIC_CHAT_MISC					0.0
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.0
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.0
	CHARACTERISTIC_CHAT_KILL					0.0
	CHARACTERISTIC_CHAT_DEATH					0.0
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.0
	CHARACTERISTIC_CHAT_HITTALKING				0.0
	CHARACTERISTIC_CHAT_HITNODEATH				0.0
	CHARACTERISTIC_CHAT_HITNOKILL				0.0
	CHARACTERISTIC_CHAT_RANDOM					0.0
	CHARACTERISTIC_CHAT_REPLY					0.0

	CHARACTERISTIC_CROUCHER						0.0
	CHARACTERISTIC_JUMPER						1.0
	CHARACTERISTIC_WEAPONJUMPING				0.6
	CHARACTERISTIC_GRAPPLE_USER					0.2

	CHARACTERISTIC_ITEMWEIGHTS					"bots/mccormick_i.c"
	CHARACTERISTIC_AGGRESSION					0.8
	CHARACTERISTIC_SELFPRESERVATION				0.2
	CHARACTERISTIC_VENGEFULNESS					0.75
	CHARACTERISTIC_CAMPER						0.3

	CHARACTERISTIC_EASY_FRAGGER					0.9
	CHARACTERISTIC_ALERTNESS					0.7

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.8
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.85
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.75
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.65
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		0.65
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.85
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.65
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.65
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.55
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.45
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.65
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.35

	CHARACTERISTIC_FIRETHROTTLE					0.85
}