//------------------------------------------------
//TheSwat_c.c
//------------------------------------------------
// TheSwat - Version Ver1.0SWAT
// Created By: Martinus with the Quake ToolKit (www.planetquake.com/eoc)
//             Martinus001@gmail.com
// -
//
// Local agent of S.W.A.T.
// A very special unit, who can keep 
// everithing under control and safe...
// If... he could keep himself normal
// but... he isn't normal anymore!!!
// 
// He is a real scumbag, be careful!
// (I tried to not use bad words... too 
// often.)
//------------------------------------------------

#include "chars.h"

skill 1
{
CHARACTERISTIC_NAME                            "TheSwat"
CHARACTERISTIC_GENDER                          "Male"
CHARACTERISTIC_ATTACK_SKILL                    0.5
CHARACTERISTIC_WEAPONWEIGHTS                   "bots/TheSwat_w.c"
CHARACTERISTIC_AIM_SKILL                       0.06
CHARACTERISTIC_AIM_ACCURACY                    0.29
CHARACTERISTIC_VIEW_FACTOR                     0.11
CHARACTERISTIC_VIEW_MAXCHANGE                  268
CHARACTERISTIC_REACTIONTIME                    2.02

CHARACTERISTIC_CHAT_FILE                       "bots/TheSwat_t.c"
CHARACTERISTIC_CHAT_NAME                       "TheSwat"
CHARACTERISTIC_CHAT_CPM                        121
CHARACTERISTIC_CHAT_INSULT                     0.49
CHARACTERISTIC_CHAT_MISC                       0.5
CHARACTERISTIC_CHAT_STARTENDLEVEL              0.46
CHARACTERISTIC_CHAT_ENTEREXITGAME              0.5
CHARACTERISTIC_CHAT_KILL                       0.56
CHARACTERISTIC_CHAT_DEATH                      0.54
CHARACTERISTIC_CHAT_ENEMYSUICIDE               0.54
CHARACTERISTIC_CHAT_HITTALKING                 0.48
CHARACTERISTIC_CHAT_HITNODEATH                 0.48
CHARACTERISTIC_CHAT_HITNOKILL                  0.49
CHARACTERISTIC_CHAT_RANDOM                     0.49
CHARACTERISTIC_CHAT_REPLY                      0.5

CHARACTERISTIC_CROUCHER                        0.08
CHARACTERISTIC_JUMPER                          0.4
CHARACTERISTIC_WEAPONJUMPING                   0.79
CHARACTERISTIC_GRAPPLE_USER                    0.05
CHARACTERISTIC_WALKER                          0.05

CHARACTERISTIC_ITEMWEIGHTS                     "bots/TheSwat_i.c"
CHARACTERISTIC_AGGRESSION                      0.01
CHARACTERISTIC_SELFPRESERVATION                0.49
CHARACTERISTIC_VENGEFULNESS                    0.82
CHARACTERISTIC_CAMPER                          0.1

CHARACTERISTIC_EASY_FRAGGER                    1
CHARACTERISTIC_ALERTNESS                       0.47

CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN         0.46
CHARACTERISTIC_AIM_ACCURACY_SHOTGUN            0.45
CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER     0.39
CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER    0.26
CHARACTERISTIC_AIM_ACCURACY_LIGHTNING          0.73
CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN          0.43
CHARACTERISTIC_AIM_ACCURACY_RAILGUN            0.82
CHARACTERISTIC_AIM_ACCURACY_BFG10K             0.56
CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER        0.56
CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER       0.26
CHARACTERISTIC_AIM_SKILL_PLASMAGUN             0.73
CHARACTERISTIC_AIM_SKILL_BFG10K                0.78

CHARACTERISTIC_FIRETHROTTLE                    0.5
}

skill 4
{
CHARACTERISTIC_NAME                            "TheSwat"
CHARACTERISTIC_GENDER                          "Male"
CHARACTERISTIC_ATTACK_SKILL                    0.57
CHARACTERISTIC_WEAPONWEIGHTS                   "bots/TheSwat_w.c"
CHARACTERISTIC_AIM_SKILL                       0.6
CHARACTERISTIC_AIM_ACCURACY                    0.68
CHARACTERISTIC_VIEW_FACTOR                     0.39
CHARACTERISTIC_VIEW_MAXCHANGE                  268
CHARACTERISTIC_REACTIONTIME                    2.28

CHARACTERISTIC_CHAT_FILE                       "bots/TheSwat_t.c"
CHARACTERISTIC_CHAT_NAME                       "TheSwat"
CHARACTERISTIC_CHAT_CPM                        121
CHARACTERISTIC_CHAT_INSULT                     0.49
CHARACTERISTIC_CHAT_MISC                       0.5
CHARACTERISTIC_CHAT_STARTENDLEVEL              0.46
CHARACTERISTIC_CHAT_ENTEREXITGAME              0.5
CHARACTERISTIC_CHAT_KILL                       0.56
CHARACTERISTIC_CHAT_DEATH                      0.54
CHARACTERISTIC_CHAT_ENEMYSUICIDE               0.54
CHARACTERISTIC_CHAT_HITTALKING                 0.48
CHARACTERISTIC_CHAT_HITNODEATH                 0.48
CHARACTERISTIC_CHAT_HITNOKILL                  0.49
CHARACTERISTIC_CHAT_RANDOM                     0.49
CHARACTERISTIC_CHAT_REPLY                      0.5

CHARACTERISTIC_CROUCHER                        0.08
CHARACTERISTIC_JUMPER                          0.4
CHARACTERISTIC_WEAPONJUMPING                   0.79
CHARACTERISTIC_GRAPPLE_USER                    0.05
CHARACTERISTIC_WALKER                          0.08

CHARACTERISTIC_ITEMWEIGHTS                     "bots/TheSwat_i.c"
CHARACTERISTIC_AGGRESSION                      1
CHARACTERISTIC_SELFPRESERVATION                0.49
CHARACTERISTIC_VENGEFULNESS                    0.87
CHARACTERISTIC_CAMPER                          0.21

CHARACTERISTIC_EASY_FRAGGER                    1
CHARACTERISTIC_ALERTNESS                       0.47

CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN         0.85
CHARACTERISTIC_AIM_ACCURACY_SHOTGUN            0.84
CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER     0.39
CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER    0.26
CHARACTERISTIC_AIM_ACCURACY_LIGHTNING          0.82
CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN          0.56
CHARACTERISTIC_AIM_ACCURACY_RAILGUN            1
CHARACTERISTIC_AIM_ACCURACY_BFG10K             0.56
CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER        0.73
CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER       0.41
CHARACTERISTIC_AIM_SKILL_PLASMAGUN             0.79
CHARACTERISTIC_AIM_SKILL_BFG10K                0.78

CHARACTERISTIC_FIRETHROTTLE                    0.5
}

skill 5
{
CHARACTERISTIC_NAME                            "TheSwat"
CHARACTERISTIC_GENDER                          "Male"
CHARACTERISTIC_ATTACK_SKILL                    0.66
CHARACTERISTIC_WEAPONWEIGHTS                   "bots/TheSwat_w.c"
CHARACTERISTIC_AIM_SKILL                       0.82
CHARACTERISTIC_AIM_ACCURACY                    0.68
CHARACTERISTIC_VIEW_FACTOR                     0.97
CHARACTERISTIC_VIEW_MAXCHANGE                  268
CHARACTERISTIC_REACTIONTIME                    2.32

CHARACTERISTIC_CHAT_FILE                       "bots/TheSwat_t.c"
CHARACTERISTIC_CHAT_NAME                       "TheSwat"
CHARACTERISTIC_CHAT_CPM                        121
CHARACTERISTIC_CHAT_INSULT                     0.49
CHARACTERISTIC_CHAT_MISC                       0.5
CHARACTERISTIC_CHAT_STARTENDLEVEL              0.46
CHARACTERISTIC_CHAT_ENTEREXITGAME              0.5
CHARACTERISTIC_CHAT_KILL                       0.56
CHARACTERISTIC_CHAT_DEATH                      0.54
CHARACTERISTIC_CHAT_ENEMYSUICIDE               0.54
CHARACTERISTIC_CHAT_HITTALKING                 0.48
CHARACTERISTIC_CHAT_HITNODEATH                 0.48
CHARACTERISTIC_CHAT_HITNOKILL                  0.49
CHARACTERISTIC_CHAT_RANDOM                     0.49
CHARACTERISTIC_CHAT_REPLY                      0.5

CHARACTERISTIC_CROUCHER                        0.08
CHARACTERISTIC_JUMPER                          0.4
CHARACTERISTIC_WEAPONJUMPING                   0.79
CHARACTERISTIC_GRAPPLE_USER                    0.05
CHARACTERISTIC_WALKER                          0.08

CHARACTERISTIC_ITEMWEIGHTS                     "bots/TheSwat_i.c"
CHARACTERISTIC_AGGRESSION                      1
CHARACTERISTIC_SELFPRESERVATION                0.49
CHARACTERISTIC_VENGEFULNESS                    1
CHARACTERISTIC_CAMPER                          0.4

CHARACTERISTIC_EASY_FRAGGER                    1
CHARACTERISTIC_ALERTNESS                       0.47

CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN         1
CHARACTERISTIC_AIM_ACCURACY_SHOTGUN            1
CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER     0.39
CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER    0.26
CHARACTERISTIC_AIM_ACCURACY_LIGHTNING          1
CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN          0.75
CHARACTERISTIC_AIM_ACCURACY_RAILGUN            1
CHARACTERISTIC_AIM_ACCURACY_BFG10K             0.56
CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER        0.82
CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER       0.57
CHARACTERISTIC_AIM_SKILL_PLASMAGUN             0.92
CHARACTERISTIC_AIM_SKILL_BFG10K                0.78

CHARACTERISTIC_FIRETHROTTLE                    0.9
}
