//KM shader file plz don't modify cause it's generated by quake God bless Carmack btw

textures/dm12/city
{
	surfaceparm nolightmap
	surfaceparm noimpact
	surfaceparm nomarks
	surfaceparm sky
	q3map_surfacelight 80
	q3map_sun 1 1 1 40 100 37 //R G B Intens(65) Deg Elev(30)
	skyparms env/city 128 128
}

textures/dm12/torchflame
{
	qer_editorimage textures/dm12/fire/flame_01.tga
	q3map_lightimage textures/dm12/fire/flame_01.tga	
	surfaceparm trans
	surfaceparm noimpact
	surfaceparm nolightmap
	surfaceparm nonsolid
	surfaceparm nomarks
	nopicmip
	cull none
	q3map_surfacelight 60
	q3map_backSplash 10 15 //percent distance
	q3map_cnq3_depthFade 1 0
	deformVertexes autosprite2
	{
		clampmap textures/dm12/fire/flameball.jpg
		blendFunc add
		rgbGen wave sin 0.25 0.1 0 0.4
		tcMod transform 2 0 0 1 -0.5 0
	}
	{
		animMap 32 textures/dm12/fire/flame_01.tga textures/dm12/fire/flame_02.tga textures/dm12/fire/flame_03.tga textures/dm12/fire/flame_04.tga textures/dm12/fire/flame_05.tga textures/dm12/fire/flame_06.tga textures/dm12/fire/flame_07.tga textures/dm12/fire/flame_08.tga
		blendFunc add
		rgbGen wave square 0.5 0.5 0 2
	}
	{
		animMap 32 textures/dm12/fire/flame_09.tga textures/dm12/fire/flame_10.tga textures/dm12/fire/flame_11.tga textures/dm12/fire/flame_12.tga textures/dm12/fire/flame_13.tga textures/dm12/fire/flame_14.tga textures/dm12/fire/flame_15.tga textures/dm12/fire/flame_16.tga
		blendFunc add
		rgbGen wave square 0.5 0.5 0.5 2
	}
}

textures/dm12/proto_grate4
{      
	q3map_vertexScale 1.50   
	cull disable
	surfaceparm trans
	surfaceparm alphashadow
	surfaceparm nolightmap  
	{
		map textures/dm12/proto_grate4.tga 
                alphaFunc GE128
                depthWrite
		rgbGen vertex
	}
}

//lights:
textures/dm12/ph_ltn
{
	qer_editorimage textures/dm12/ph_ltn.tga
	surfaceparm nomarks
	q3map_surfacelight 1250
	//nopicmip
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/dm12/ph_ltn.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/dm12/ph_ltn_blend.tga
		blendfunc GL_ONE GL_ONE
	}
}

textures/dm12/ceil38
{
	surfaceparm nomarks
	q3map_surfacelight 1800
	//nopicmip
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/dm12/ceil38.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/dm12/ceil38_blend.tga
		blendfunc GL_ONE GL_ONE
	}
}

textures/dm12/eu_light1
{
	qer_editorimage textures/dm12/eu_light1.tga
	q3map_surfacelight 450
	//nopicmip
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/dm12/eu_light1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/dm12/eu_light1_blend.tga
		blendfunc GL_ONE GL_ONE
	}
}

textures/dm12/beam
{
        surfaceparm trans	
        surfaceparm nomarks	
        surfaceparm nonsolid
	surfaceparm nolightmap
	nopicmip
	cull none	
	{
		map textures/dm12/beam.tga
                tcMod Scroll .3 0
                blendFunc add
        }
}

//BR logo nomip:
textures/dm12/br_logo
{
	qer_editorimage textures/dm12/br_logo.tga
	nopicmip
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/dm12/br_logo.tga
		rgbGen identity
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

//slime effects:
textures/dm12/moats_g
{
	qer_alphafunc greater 0.5
	qer_trans 0.6
	qer_nocarve
	qer_editorimage textures/dm12/moats_g.jpg
	surfaceparm trans	
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm nodlight
	surfaceparm nolightmap
	cull none
	nopicmip
	deformVertexes bulge 128 1 2	
	{
		map textures/dm12/moats_g.jpg
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen vertex
        	tcMod turb 0 .07 0 .22
		tcMod scroll 0 .12
	}
}

textures/dm12/slime
{
	qer_editorimage textures/dm12/slime.jpg
	qer_nocarve
	qer_trans 0.9
	q3map_globaltexture
	surfaceparm noimpact
	surfaceparm slime
	sort 6
	q3map_lightmapSampleOffset -8
	q3map_surfacelight 100
	q3map_backSplash 0 4
	q3map_cnq3_depthfade 10 0
	tesssize 32
	nopicmip
	cull disable
	deformVertexes wave 40 sin 0 2.5 0 0.05
    {
        	map textures/dm12/slime.jpg
        	blendFunc blend
        	rgbGen const ( 0.35 0.35 0.35 )
        	tcMod turb 0 0.02 0 0.17
    }
}

textures/dm12/slime_fog
{
	qer_editorimage textures/dm12/slime_fog.jpg
	qer_trans 0.4
	q3map_globaltexture
	surfaceparm trans
	surfaceparm nonsolid
	surfaceparm fog    
	surfaceparm nolightmap            
	cull disable
	fogparms ( 0.1 0.5 0.1 ) 250
}

//trans grates:
textures/dm12/chain-fence
{      
	q3map_vertexScale 1.50
	qer_trans 0.7
	cull disable
	surfaceparm trans
	surfaceparm alphashadow
	surfaceparm nolightmap  
	{
		map textures/dm12/chain-fence.tga 
                alphaFunc GE128
                depthWrite
		rgbGen vertex
	}
}

textures/dm12/eu_floortile5_
{
	cull disable
	surfaceparm alphashadow
	surfaceparm trans
	surfaceparm nomarks
	nopicmip
	{
		map textures/dm12/eu_floortile5_.tga
                alphaFunc GE128
		depthWrite
	}
	{
		map $lightmap
		rgbGen identity
		blendFunc filter
		depthFunc equal
	}
}

//plants vs zombies:
textures/dm12/plant_leaf1
{
	qer_editorimage textures/dm12/plant_leaf1.tga
	q3map_lightimage textures/dm12/plant_leaf1.tga
	qer_trans 1
	qer_alphafunc greater 0.5	
	surfaceparm alphashadow
	q3map_vertexScale 2
	surfaceparm trans
	surfaceparm nonsolid
	surfaceparm nomarks
	surfaceparm nolightmap	
	cull none
	nopicmip
	deformVertexes wave 25 sin 0 1 0 0.08 //base amp phase freq
	{
		map textures/dm12/plant_leaf1.tga
		alphaFunc GE128
		rgbGen vertex
		depthWrite
	}	
}

textures/dm12/plant_leaf2
{
	qer_editorimage textures/dm12/plant_leaf2.tga
	q3map_lightimage textures/dm12/plant_leaf2.tga
	qer_trans 1
	qer_alphafunc greater 0.5	
	surfaceparm alphashadow
	q3map_vertexScale 2
	surfaceparm trans
	surfaceparm nonsolid
	surfaceparm nomarks
	surfaceparm nolightmap	
	cull none
	nopicmip
	deformVertexes wave 25 sin 0 1 0 0.08 //base amp phase freq
	{
		map textures/dm12/plant_leaf2.tga
		alphaFunc GE128
		rgbGen vertex
		depthWrite
	}	
}

textures/dm12/vine06
{
	qer_editorimage textures/dm12/vine06.tga
	q3map_lightimage textures/dm12/vine06.tga
	qer_trans 1
	qer_alphafunc greater 0.5	
	surfaceparm alphashadow
	q3map_vertexScale 2
	surfaceparm trans
	surfaceparm nonsolid
	surfaceparm nomarks
	surfaceparm nolightmap	
	nopicmip
	cull none
	deformVertexes wave 25 sin 0 2 0 0.1 
	{
		map textures/dm12/vine06.tga
		alphaFunc GE128
		rgbGen vertex
		depthWrite
	}	
}

//decals:
textures/dm12/logo_genArc
{
    qer_editorImage textures/dm12/logo_genArc.tga
    surfaceparm nonsolid
    surfaceparm nodlight
    surfaceparm nomarks
    surfaceparm trans
    surfaceparm detail
    polygonOffset
    nopicmip
    {
        map textures/dm12/logo_genArc.tga
        rgbGen const ( .37 .37 .37 )
        blendFunc add
    }
}

textures/dm12/dec-memento
{
	polygonOffset
	surfaceparm nonsolid
	surfaceparm nomarks
	nopicmip
	{
		map textures/dm12/dec-memento.tga
		rgbGen const ( .9 .9 .9 )
		blendFunc GL_ZERO GL_ONE_MINUS_SRC_COLOR
		detail
	}
}

//nonsolid:
textures/dm12/metal10noc
{
	qer_editorimage textures/dm12/metal10noc.tga
	surfaceparm nonsolid
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/dm12/metal10noc.tga
		rgbGen identity
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

textures/dm12/arr29
{
	qer_editorimage textures/dm12/arr29.tga
	surfaceparm nonsolid
	nopicmip
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/dm12/arr29.tga
		rgbGen identity
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

//glass:
textures/dm12/glass
{
        qer_editorimage textures/dm12/glass.tga
        qer_trans 0.50
        surfaceparm nolightmap
	surfaceparm nodlight
        surfaceparm trans
        {
                map textures/dm12/glass.tga
                blendfunc filter
		rgbGen identity
        }
        {
                map textures/dm12/glass_env.tga
                blendfunc add
                rgbGen identity
                tcGen environment
        }
}

textures/dm12/glass_break_c
{
	qer_editorimage textures/dm12/glass_break_c.tga
	qer_trans 0.9
	surfaceparm nolightmap
	surfaceparm nodlight
	surfaceparm trans
	sort additive
	{
		map textures/dm12/glass_break_c.tga
		blendfunc filter
		rgbGen identity
		depthWrite
		alphaFunc GE128
	}
	{
		map textures/dm12/glass_env.tga
		blendfunc add
		rgbGen identity
		tcGen environment
		depthFunc equal
	}
}

//jumppad energy flow:
textures/dm12/jp/alpha_vert
{
    qer_editorimage textures/dm12/jp/alpha_vert.tga
    qer_trans .5
    surfaceparm nonsolid
    surfaceparm nodraw
    surfaceparm trans
    q3map_alphaMod volume    <-sets a brush to alter the vertices it overlaps
    q3map_alphaMod set 0     <-sets the value of the v alpha given
}

// 2 groups of cyan electric beams with 3 beams per group. each group goes up, rotates and changes intensity at different speeds
// 2 groups of white trails. each group has its own trail size and speed
textures/dm12/jp/01
{
	qer_editorimage textures/dm12/jp/01.tga
	qer_trans 0
	surfaceparm nodlight
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
	cull none
	nopicmip
	deformVertexes wave 200 sin 0 2 0 0.37
	q3map_lightimage textures/dm12/jp/01.tga
	q3map_surfacelight 65 //85
	q3map_backSplash 10 25

	{
		animMap 16 textures/dm12/jp/01.tga textures/dm12/jp/02.tga textures/dm12/jp/03.tga textures/dm12/jp/04.tga textures/dm12/jp/05.tga textures/dm12/jp/06.tga textures/dm12/jp/07.tga textures/dm12/jp/08.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.8 0.2 0 0.3
		alphaGen vertex
		tcMod transform 0 -0.5 0.5 0 0 0
		tcMod scroll -0.7 0.17
	}
	{
		animMap 16 textures/dm12/jp/01.tga textures/dm12/jp/02.tga textures/dm12/jp/03.tga textures/dm12/jp/04.tga textures/dm12/jp/05.tga textures/dm12/jp/06.tga textures/dm12/jp/07.tga textures/dm12/jp/08.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.8 0.2 0 0.5
		alphaGen vertex
		tcMod transform 0 -0.5 0.5 0 0 0.5
		tcMod scroll -1.1 -0.13
	}
	{
		map textures/dm12/jp/omfgstars.jpg
		blendFunc GL_SRC_ALPHA GL_ONE
		alphaGen vertex
		tcMod scale 2 0.125
		tcMod scroll 0 -0.23
	}
	{
		map textures/dm12/jp/omfgstars.jpg
		blendFunc GL_SRC_ALPHA GL_ONE
		alphaGen vertex
		tcMod scale 1 0.0625
		tcMod scroll 0 -0.17
	}
}

textures/dm12/jp/jp_fx
{
	qer_editorimage textures/dm12/jp/jp_fx.tga
	surfaceparm nolightmap
	surfaceparm nonsolid
	surfaceparm noimpact
	surfaceparm nomarks
	surfaceparm trans
	nopicmip
	cull none
	{
		map textures/dm12/jp/jp_particles.tga
		alphaGen vertex
		tcMod scale .125 .125
		tcMod turb 0 .1 0 .05
		tcMod scroll 0 .1
		blendFunc GL_SRC_ALPHA GL_ONE
	}
}

textures/dm12/jp/jp_fx_fast
{
	qer_editorimage textures/dm12/jp/jp_fx.tga
	surfaceparm nolightmap
	surfaceparm nonsolid
	surfaceparm noimpact
	surfaceparm nomarks
	surfaceparm trans
	nopicmip
	cull none
	{
		map textures/dm12/jp/jp_particles.tga
		alphaGen vertex
		tcMod scale .14 .14
		tcMod turb 0 .07 0 .04
		tcMod scroll 0 1.2
		blendFunc GL_SRC_ALPHA GL_ONE
	}
}

//item pads:
textures/dm12/dec-pwr
{
	qer_editorimage textures/dm12/dec-pwr.tga
	surfaceparm trans
	surfaceparm nomarks
	q3map_surfacelight 100
	polygonoffset
	sort 6
	nopicmip
	cull none

	{
		map textures/dm12/dec-pwr.tga
		blendFunc add
		rgbGen wave sin .5 .45 0 .6
	}
}

textures/dm12/dec-mh
{
	qer_editorimage textures/dm12/dec-mh.tga
	surfaceparm trans
	surfaceparm nomarks
	q3map_surfacelight 100
	polygonoffset
	sort 6
	nopicmip
	cull none

	{
		map textures/dm12/dec-mh.tga
		blendFunc add
		rgbGen wave sin .5 .45 0 .6
	}
}

textures/dm12/dec-ra
{
	qer_editorimage textures/dm12/dec-ra.tga
	surfaceparm trans
	surfaceparm nomarks
	q3map_surfacelight 100
	polygonoffset
	sort 6
	nopicmip
	cull none

	{
		map textures/dm12/dec-ra.tga
		blendFunc add
		rgbGen wave sin .5 .45 0 .6
	}
}

textures/dm12/dec-ya
{
	qer_editorimage textures/dm12/dec-ya.tga
	surfaceparm trans
	surfaceparm nomarks
	q3map_surfacelight 100
	polygonoffset
	sort 6
	nopicmip
	cull none

	{
		map textures/dm12/dec-ya.tga
		blendFunc add
		rgbGen wave sin .5 .45 0 .6
	}
}

textures/dm12/dec-ga
{
	qer_editorimage textures/dm12/dec-ga.tga
	surfaceparm trans
	surfaceparm nomarks
	q3map_surfacelight 100
	polygonoffset
	sort 6
	nopicmip
	cull none

	{
		map textures/dm12/dec-ga.tga
		blendFunc add
		rgbGen wave sin .5 .45 0 .6
	}
}

textures/dm12/dec-ws
{
	qer_editorimage textures/dm12/dec-ws.tga
	surfaceparm trans
	surfaceparm nomarks
	q3map_surfacelight 100
	polygonoffset
	sort 6
	nopicmip
	cull none

	{
		map textures/dm12/dec-ws.tga
		blendFunc add
		rgbGen wave sin .5 .45 0 .6
	}
}