// Custom shader file for dm1.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

dm1/57D8E0E7A89244E2C36F1139F02925EF
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.86
	{
		map textures/dm1/rox0172.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0006.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/3C4DE628ABACB9D5CD29848F9126166A
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.86
	{
		map textures/dm1/rox0172.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0008.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/DAE1F996E8AF3C14F0568440AB159A05
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/brix0029.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/04A1D9AFEC2F573C4A1581CBA85AA650
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/brix0029.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/D0F052C6DF059D6DF4977BC2C0E08DBF
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/brix0029.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/91DCF0DCDD2DAE5EE8EC9EAEE4D95DC9
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/brix0029.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/3498CC6BEFDBDF8D1B8D022638AC6C5E
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/brix0029.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/8C6CA00DA778BD737B47C38E8E5ACE22
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/brix0029.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/0718FA9CC5072B5A5230100FBC09F7B1
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/brix0029_.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/8F680B742BD834327DF26712C83F882B
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/brix0029_.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/DC9C79D39590417A6D1D4AD4EBAD9BC7
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/brix0029moss.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/7D50FD9946C13D2310F4B9B701FF94A9
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/brix0029moss.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/B7462D1E0C6C4493B551D47A11C367D9
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/brix0029moss.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/EED2CF648FD8C5F7E74AD57E1B79F35F
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/conc0112.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/98113E123B4B6662CB48BAE4AABF57AA
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/conc0112.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/BDFA254F45D0025390FC7FE2399CEBF9
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/conc0112.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/D9294D93550D83A0387C97128F969AAD
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/conc0112.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/4E935D1D1C34A3A9D65438869ACEFCAB
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/conc0112a.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/73EA8ED192B2F4E6C0B2CE00CA39278D
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/conc0112a.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/DAAE6CC896B0BB798DB98B790C82740B
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/conc0112a.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/822E02D37AC4E5AFFEB90688D5D8A03E
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.36
	{
		map textures/dm1/conc0020.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/97BA82AFDD69BAC3B5204E6CA4BAFDCD
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.36
	{
		map textures/dm1/conc0020.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/C44B7A8948CCE68D892D06903D06DAD7
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.36
	{
		map textures/dm1/conc0020.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/CA3EE142617758A984AB6B827D360168
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/crete_kfs.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/DA6000AAE41A8E266CB197FCC7554D2F
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/crete_kfs.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/DBA1BAC2F46323A2C18CAC9656D78FE5
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/crete_kfs.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/ED2F08A1CF6ACEEBDF846B64B8A76337
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/crete_kfs.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/758BBA4F21EA199D7CC2DF19A6F10E45
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/ph_conc.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/BCDA59AD12DE44ED9566C2DD432A6848
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/ph_conc.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/2CAFC11CD435110095AC7760CD718B44
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/ph_conc.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/C2362C360539263989A03BB1A59C9CCC
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/ph_conc.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/F502FDB378B3763188B05A163B401DEF
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/ph_conc.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/CF5EC836EBF9DD0926CE28E328DBD18D
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/ph_conc.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/13E441F90FA532942EF56CBBE8E4CA41
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/ph_conc512.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/BFC0664D94D701992F20D79A81935385
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/ph_conc512.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/00FFBE28E11222B4231A83E5F5868079
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/ph_conc512.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/2C3A532C5CEC5AF82BC0434FB4AE3638
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/ph_conc512.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/5A05DC8D1E3CEA507439BD71688F7B74
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/ph_conc512.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/6344A472097FE4785F38316BA0D87082
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/ph_conc512.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/43D4DBD0973AA3A21E5A1B9104A9B93D
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/ph_conc512.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0006.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/8514C4B3B8779BBC5734EFF1DE2F4C16
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/metb_.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/97A72540F140F91A64C37FDBAA42CBC3
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/metb_.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/761B1ECD0BF79FBE42D4D980E61EA034
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/metb_.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/000A62CEB6D9A7FE1BE30E05C7E4EC18
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/metb_.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/993067DDF9E0BD5CB1CA061595F29B91
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/metb_.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/23CC576454A466A35C58F9AC37643EE5
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/metb_.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/2D7A710493194CE8D8F57E03B9E89FC0
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/metal_2.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/C083F2D2D8381900884FA1FE45DE2669
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/metal_2.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/2C271AFB5ABA38BF716A0AE7A0BB8D46
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/metal_2.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/0588B64B8B135B6B501A79148792BD29
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/metal_2.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/BA0708F173C9F4FF74594B498D22B7B2
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.96
	{
		map textures/dm1/flr_hex27.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/8D3492BDF5077D4E9AC12A8E1730CD0A
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.96
	{
		map textures/dm1/flr_hex27.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/E1D998718A79F677E9D81C97AFBEFB3A
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.96
	{
		map textures/dm1/flr_hex27.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/C243C65CF102982A440A62CDBB71F982
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/tile0071.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/DE5F2E25C10287C1D44F7F255DD918A7
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/tile0071.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/8A9975FFBAF3EBC1B435BFEA0667B50C
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/tile0071.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/2649FAFBB8994850C4BC4D711528A4B1
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/tile0071.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/82E020F7209C39149CC95169D38CD34C
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/tile0071.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/2D523EC13ADDE4D816FB4121D559C942
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/tile0071.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0006.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/8BDB18AB7A25B9962F87D07AD7F8779B
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/flr_004.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/444DB0FC432AAEEAD95D0C7D5F818353
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/flr_004.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/6AD1B1FDB2101C2F9ECAECA022303408
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/flr_004.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/618A008E771AFCFDF7DE66B4611ABD87
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/flr_017.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/6462D561A8B60B84F92396336CA60162
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/flr_017.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/247D7E94EB3587595DCD3DD82FBA018E
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/flr_084.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/58DE5C79171E481A4A1BD9F61686C5CB
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/flr_084.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/CF3379CBE67BFF47AFF72A8DAC63BD9B
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/flr_084.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/316F2296DCB544B48EEB4AD22A475FF2
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.6
	{
		map textures/dm1/cont005.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/7C60C4B272D0769EC3245105A40096BB
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.6
	{
		map textures/dm1/cont005.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/1CA8B25E46C225491BFD822B712D1E4E
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.6
	{
		map textures/dm1/cont072.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/8D7F1B9256DEF66F0201C7F1E57FFA34
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.6
	{
		map textures/dm1/cont072.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/DC25DF9CB68C3DD04145DD3ABB42CE6A
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.6
	{
		map textures/dm1/cont182.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/03C2EC4190045E86C38D8068E1142C3B
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.6
	{
		map textures/dm1/cont182.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/3DE0A5F0E14BC5A312BEDBFADA4D774B
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.6
	{
		map textures/dm1/cont0027d.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/CAFE365A3DB1A785049354BAFD604AAC
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.6
	{
		map textures/dm1/cont089.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/7553AA3BB937609E9A37B025C3B1E95D
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.6
	{
		map textures/dm1/wind0348.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0007.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/F1C65EDC729DC9063FE61E1F0D6EB4B2
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.6
	{
		map textures/dm1/wind0348.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0008.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/0DE1CE99A15B6B4B9DA92CA57C5E2886
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.6
	{
		map textures/dm1/wind0348.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0009.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/A062B030BF6B39AA9439528C9A4548BA
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.6
	{
		map textures/dm1/wind0348.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/2C9AC117C3996B34116976A8C5678C6B
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.6
	{
		map textures/dm1/wind0348.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0006.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/0733E2D55E2F9D44C3F6F09E00DCABBF
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm1/wind0454.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/850080140293F832EC68E11FB164A40F
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.86
	{
		map textures/dm1/rox0172.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm1/lm_0007.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm1/0978FDCE041D7B6E8DC948B8643EA518
{
	qer_editorimage textures/dm1/ph_slime.tga
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	q3map_globaltexture
	qer_nocarve
	qer_trans .7
	surfaceparm trans
	surfaceparm nonsolid
	surfaceparm water
	sort 6
	cull disable
	nopicmip
	{
		map textures/dm1/ph_slime_1.tga
		blendfunc GL_ONE GL_ONE
		tcMod scroll .02 .02
	}
	{
		map textures/dm1/ph_poolpass.tga
		blendfunc GL_ONE GL_ONE
		tcMod scale .5 .6
		tcMod scroll .06 .04
	}
	{
		map textures/dm1/ph_slime.tga
		blendfunc GL_ONE GL_ONE
		tcMod scroll .05 .05
	}
	{
		map maps/dm1/lm_0005.tga
		tcgen lightmap
		tcgen lightmap
		rgbGen identityLighting
		blendfunc GL_DST_COLOR GL_ZERO
	}
}

dm1/7EF8337F9F5A3554EFD59A7C4F59E299
{
	qer_editorimage textures/dm1/ph_slime.tga
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	q3map_globaltexture
	qer_nocarve
	qer_trans .7
	surfaceparm trans
	surfaceparm nonsolid
	surfaceparm water
	sort 6
	cull disable
	nopicmip
	{
		map textures/dm1/ph_slime_1.tga
		blendfunc GL_ONE GL_ONE
		tcMod scroll .02 .02
	}
	{
		map textures/dm1/ph_poolpass.tga
		blendfunc GL_ONE GL_ONE
		tcMod scale .5 .6
		tcMod scroll .06 .04
	}
	{
		map textures/dm1/ph_slime.tga
		blendfunc GL_ONE GL_ONE
		tcMod scroll .05 .05
	}
	{
		map maps/dm1/lm_0007.tga
		tcgen lightmap
		tcgen lightmap
		rgbGen identityLighting
		blendfunc GL_DST_COLOR GL_ZERO
	}
}

