// Custom shader file for dm3.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

dm3/FDF0F905893F621CCDAD64D19138F9CE
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm3/k_floor09a.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/436BC71C25D605D0846DFBA024F8E274
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/eU_tp2.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/EB9E498FC042164845B825C13BDA6873
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/k_wall03a.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/6F18D5046F4920FE39790C8DAE094892
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.82
	{
		map textures/dm3/metb_.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/280AF8B9D5BBE91B9148A68602760EF2
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.8
	{
		map textures/dm3/ph_rox.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/D9AB72132DA3BD82BDB6736221D4AC9D
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.8
	{
		map textures/dm3/rox0172.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/551A7B82747B4481AE849F4732F90CBA
{
	qer_editorimage textures/dm3/rox0172.tga
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.8
	surfaceparm slick
	{
		map textures/dm3/rox0172.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/9DA9DDC6419C6349BF5B0F7546A519E1
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/eU_wp6.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/9A1349B96B3A1E8CB732291FD8788511
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/metal_6.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/0E287653A4DB6962676F5D2360B649D7
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.82
	{
		map textures/dm3/metb_.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/FDBB4EA5C970403ACA590D7EA51A26C4
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.98
	{
		map textures/dm3/eU_wallrib.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/83E34453C8FE2EC6A68A6EBBD2D4FAAC
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/eu_clang.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/ABEA5898CA502F69CD45F03C18358B1E
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm3/k_floor09a.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/DEDD995E729D041A55A19D59CBA2AB71
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/eU_wp4_.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/B09D8D823F9FF881C4099406EE0BEDDE
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/eU_wp4_.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/FE29BC3F7DFCB134B2C653784A4ED8D9
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/eU_wp1.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/C8A48ED77E1C7A6547665CF15071B83F
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/eU_wp1.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/D111BED6F0306E32FBD0DF79A127ED40
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.9
	{
		map textures/dm3/plast_blu_leak.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/968C75101FCFF41801D07561CCF34EA3
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.9
	{
		map textures/dm3/plast_blu_leak.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/2F7CAE27A11C87EDBEB0BAA85B1421AE
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.8
	{
		map textures/dm3/rox0172.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/05DA65E5BD2C318D345E04D468545856
{
	qer_editorimage textures/dm3/ph_rox.tga
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.8
	surfaceparm slick
	{
		map textures/dm3/ph_rox.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/4612033D343D3ED9D382774B8D7603DE
{
	qer_editorimage textures/dm3/ph_rox.tga
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.8
	surfaceparm slick
	{
		map textures/dm3/ph_rox.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/CA5D54AB40364CC7423DCE985DB79B97
{
	qer_editorimage textures/dm3/rox0172.tga
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.8
	surfaceparm slick
	{
		map textures/dm3/rox0172.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/A4938BCF2F340A1059AF9DB616AE3A7A
{
	qer_editorimage textures/dm3/ph_conc512.tga
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.97
	surfaceparm slick
	{
		map textures/dm3/ph_conc512.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/CF71C6F882274DB79968C75C352CD486
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/k_wall08b.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/1FF2446F482A450EF5BB5EBC69922B84
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/k_wall08b.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/50F4002A451D4A7B75CE2F05CA4F4C22
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/k_wall03a.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/B7E6D00A6C8FCF43135E405464B344D4
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/crete_kfs.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/D2B877BFC0360273947283990C8D8EBB
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/crete_kfs.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/94E127F30EFF6B28798A787F7B4DFC24
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/beam0041.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/012EEE792F7C5C22DBF7E63AFD2E364F
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.72
	{
		map textures/dm3/flr_004_.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/6F50880D1CA1A537954AC195529E6FB1
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.72
	{
		map textures/dm3/flr_004_.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/E23A979CCAC03AF70099B8171D93DF57
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.98
	{
		map textures/dm3/eU_wallrib.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/0498FE942698D4C75DB48945C13F9638
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/eU_wp6.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/9A17E95FCEE2882D279044A75622428E
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/eU_wp2.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/AB7D48F7E1CE552E28CBDB08671ED474
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/eU_wp2.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/A824AAACD9B07D3D2BE405F1B8CB698C
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/eU_tp2.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/E985AD4DC1183FD9C1379C5527896AF4
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/eU_tp2.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/8635E5011EEEE6C0238BB62595B419E5
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/eU_flr4.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/384F6076435DEECF7E909EBB1E258EC8
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/eU_flr2.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/223D396E27FBA8F42B40F86CCE13AB71
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/eU_flr2.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/823A5A203D669167065C599A6C8041C5
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/eU_flr2warn.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/7CBB9FEFEA4FE43905C9E27EC40E6A51
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/eu_clang.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/962650CC39387986F0B21C0DA9FD132A
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.82
	{
		map textures/dm3/metb_.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/BB130FCE919690FB99E6C562049CEF6D
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/ph_conc.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/356D8D2B6B25C1FFBAAF2DC45FFB0418
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/ph_conc.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/A5ED9D633528D7D14FD29CE20F162884
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/ph_conc.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/E3C50A2AA1189905F3468A1719DFEBA9
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/ph_conc512.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/2423DDAE31519E75F0E4844A0D45AAD5
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/ph_conc512.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/A7FCB303DD41FE8AA17FFEAC67A02A21
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/ph_conc512.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/1036C6055E533437C850640017AA8004
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/metal_2.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/BEE78438AB5B0B203522CAA0A3A4D5D6
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/metal_2.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/186507735452F819C06D6E252229BC41
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/metal_2.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/DCEAB7642C71462FDFEE64E6503D3CB1
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/metal_6.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/9B2DEFD1A8CBDDE2050EEAB53B370E55
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/metal_6.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm3/87726AE431162E10EF60EA47E617BE76
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.95
	{
		map textures/dm3/eU_wp2.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm3/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

