// Custom shader file for gm3tourney2.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

gm3tourney2/84C5FF1D3CA298757267779795E4D928
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rust-basedr_wmark.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/1A7BBAF6E7D05F999F5EC9EECCE7FA31
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rt_thingnotr.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/167A38CE329FC8C522C078A0B9BE91A2
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rt_thingnotr.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/CB4E05C246DA4E83C2E3817BCEED07D2
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rt_thingnotr.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/EB19E46EFDA79C1D52941F4AB3276297
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rt_thingnotr.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/DA4EC53FCA4AB190FF114A685DB7A735
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnick2cldege.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/0E38621376882570311B775CE952D173
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnick2cldege.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/79E21851276A9576BF08CF5E267D3F6D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rust-basedr_desat.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/06C3539C05AF4C0FC3BFE4207913F510
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rust-basedr_desat.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/DB518F81F53231D5B7000AE4B41B6CAB
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnickwet.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/9C290A2891F0BA45F3B089FA6219F741
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnickwet.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/13F807ADCD9B406D511DD7422D2652EB
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnickarch.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/B2663451BCA58C89FEC9422C495FCF08
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnick2cldege.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/39B47B6BBFD5C45F9B7882240F79A058
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnickcar2stair.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/D0228F1FE323279E0D7BC50817BC6354
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnickwet_cldege.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/BB1E3DE45CF7BB92F55E662CE857566E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnickwet_cldege.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/071F267242A6779336A5737053F7183E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnickwet_cldege.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/FB60CB79D784006D970EE05EBA17D21B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rust-basedr_desat.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/9305902F807DF7B510C56BAA13F85498
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnickwet.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/D107907A826469886D447F7D506831C7
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnickwet.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/7E0989331B08896592D08B5D2B8A22E2
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnickwet.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/7E25775CF491043A524E53CF475F2DA7
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0010.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnickwet.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/4019AAB5382CCC6561BF6F41F6890262
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnickwet.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/7832461D1E78674B554CB85A7CBFAF2D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rust-basedr_wmark.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/E9874957D99A177CD51E162B7763732F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnickarch.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/A7010207471B8A27E275B7DF890D901C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rt_thingnotr.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/57597A03A2E8DCB42AE955BFCEAE5109
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnick2cldege.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/02D5D7FA8323B8D65AAF854DCBBE8882
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnick2cldege.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/8A2FAE1E8DD4BDCA46313DBF27677B1B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnick2cldege.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/D75B2B96D8BBF614477E1E91FA6FBAC8
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnickcar2stair.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/A589A08D465ECF14B2D9786AEA3CF017
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnickwet_cldege.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/136A7DA030FBBA5808D66F33EB5583B4
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnickwet_cldege.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/DE3C1334C7CC25A56209ACDA64735E7A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnickwet_cldege.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/4A59C04B19E2158665FAF74996D64A82
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnickwet_cldege.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/A48DF9E3C145E6952DF4B6E56A40825F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rust-basedr_desat.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/E2AB15A98CFCFA68757A83FFE78B1076
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0016.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rust-basedr_desat.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/3E32C4CF887FDABE0A41FFCB553D75C5
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnickwet.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/66862CFD186442123EB85F79CBDE1430
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnickwet.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm3tourney2/DD94BF3DA088AB81198A64A316184093
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/gm3tourney2/lm_0013.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.5 0.5 0 0.2 // style 1
		tcGen lightmap
	}

	{
		map textures/gm3tourney2/rtnickwet.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

