// Custom shader file for shibam.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

shibam/02617901E62BAC8558370BF8D75FBD39
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/holz2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/25051874795714FBC5AC12865D80337C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/flechtwerk1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/1A66C08C410A2B72BB94C7E00A25E7DB
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/lehm6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/ACB85F602A0C32ADDB9B81308A82FA47
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/gothic_trim/wood2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/1C462A6525FB926CC0F5622575A2C3F7
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/kiste1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/CAFFE010838A6AA66453A5EE7E977C5E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/holz2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/59AC1E43821753882A934FC642C9260F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/lehm6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/8D9379A70166EBD6778581135F161E87
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/shibam/lehm6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/C6BA19FF6242A459BF50C4B90E1AF1FA
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0016.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/lehm6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/98E3F53E0B02CA53753089C5FBD69B3B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.00781 0.29688
	}

	{
		map textures/shibam/bricks4.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/76007C75F1F721DEB6E50F166BADE101
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0017.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/lehm6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/3119A9B182B8A105B1A91A5E34CD489A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/lehm2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/AC6824E9C752B96C1700467BB0343309
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0013.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/lehm2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/BBA62CE3106CF7FFDCA787C46B1DE7AE
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.29688 0.00781
	}

	{
		map textures/shibam/palmstamm.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/40720C4797FF211A8612E731BE9B5A5F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/bricks3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/1E305753B284EE77CA0BFDFA5EF1CEA4
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/flechtwerk1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/A1499D37E15D6F53246E6A11E6B4E5E4
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/holz2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/2D5AE517034C4B4CF605B454290E8036
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/flechtwerk1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/239063C664A3615279BC10CCF8B01523
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/flechtwerk1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/C1314241DB9E9C5A9ADC518F04FF1286
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.25781 0.00000
	}

	{
		map textures/shibam/lehm6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/9F8FFB5E5746358953050454678F5C4E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0010.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/lehm6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/44BD1BFFF4F8CD6D8D38FD27B8122EF0
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.07031 0.00000
	}

	{
		map textures/shibam/bricks4.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/8A04D652692FB7B88243DEA5776D4501
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/holz2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/71EB1786429512FAFC12482AAA145053
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.37500 0.03906
	}

	{
		map textures/shibam/bricks4.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/F63C239A3B44E271A37F624C2CDF6EA1
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/base_trim/basemetalsupport.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/A2D79F935F3A1D2C6B8FCA6151FDCB90
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0021.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/shutters_3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/40EBB3FF1244474D77D9245AA0591363
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0022.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/shutters_3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/E7F5BD97AEF528A7A32F9817A6EE36C0
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/organics/dirt2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/D162D8F1A23A46B46A4F31699B5555E3
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0019.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/shibam/spices1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/811DF1F9D14FCC22389E324D13CC7302
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0019.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/spices4.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/439749B5449672619D0A1EA97D400FFE
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0022.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/spices2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/4229EE87AE3A531F8F8F4404482C5DE6
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0022.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/spices3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/D3FA37295F8FED0EF5A9388ABCDBEABD
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0010.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/kiste1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/D8996AC6CB50FA368F63338EF7C50851
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0013.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/lehm2_braun.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/0C1A67367D6DE2450146E4CD206F3108
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0019.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/lehm6_weiss.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/7333D949B71183732CF488C3E0351F52
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0018.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/lehm6_weiss.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/04E760541F6813473DECE56069EA1939
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/gothic_trim/pitted_rust.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/2382D549CB70E407BDC8DDCBDDDF4F08
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/lehm3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/28E0FF593640EB7166541833E181509F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/shibam/lehm3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/25D23B1C46A7AB21EC296170F2B3D1D5
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/shibam/lehm2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/FFFF8CDA0B9803DC6AAECA75EDA485D9
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/lehm2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/3E6B322A775A6974D67EBD86C804CA80
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/shibam/lehm2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/7B3CB154E20BDA52261B915FD718EF96
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}

	{
		map textures/shibam/lehm2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/3A05EAC73B7C99183FAD894ED436BEE2
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}

	{
		map textures/shibam/lehm2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/927162E4562D75DB0FA63D8C899FB66C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.34375 0.00781
	}

	{
		map textures/shibam/lehm2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/62E093820C4EA2788D53D99A1A17F1C6
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/lehm6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/907DA250F51BAD1D093CEC2F4C9E565B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0016.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/shibam/lehm6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/6A2E647CF6F5260241F34D366515947A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.53125 0.01563
	}

	{
		map textures/shibam/lehm6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/00182C5A476DB32043BE62255A543C88
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.00781 0.29688
	}

	{
		map textures/shibam/lehm6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/220BD8D80DA17CAE300FC42B6A763307
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0010.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/holz2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/493ABAA3798628B922EB823DF5384CBC
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/holz2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/F770A0BDFE8871B76B433261B0B2B08E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/holz2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/E4D5302EA44DB1777952F1199B1422B7
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/shibam/bricks3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/3CFED5517E42B57E7ECBA128E39A832F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/bricks3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/F33B4873A48870F536872CD542390356
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0019.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/lehm6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/46081913D1E04FF4429DBEF88E0A4B1F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0020.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/lehm6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/ADD5AD64AF41136C38D468519CC98D5C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/bricks4.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/08756F59C41D4A151B9C4087C69EB77F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/bricks4.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/F6E4911D37BC87187B71D95B42A43757
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0016.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/lehm2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/75D9FDADC651F2C51BA638F48D6560B3
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0024.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/palmstamm.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/D89E2C51C949E16EFE72187BCA577719
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0022.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/lehm6_weiss.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/BEAFF0E7A1EDD9DB687AABCEF7C85FEE
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}

	{
		map textures/shibam/flechtwerk1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/A223FCFFD47D2427BF3B332550D2B9F5
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0017.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/lehm2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/894250FFED9DADBC60AA5C8A785DD154
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/shibam/flechtwerk1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/5CC1126768C6CF31AE46EED2B7DDE263
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0019.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/shibam/lehm6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/E5315826A6282136B0B475D622161E1C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/lehm6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/B4FC974FAF1E99A222293F0CE56B5FBC
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/holz2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/7277BA06E1F16E718EF9E563F027C79D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0013.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/holz2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/0D586888280D8F1AA8F1EE2EDDB3375A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/lehm6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/2467D5D49DD22BF36022EFD364E63B26
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/bricks4.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/426BA5F0317EC0594B9F86B88835D326
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/gothic_trim/metalsupport4i_bit.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/36D82343C4D819F7F768564B9340EB26
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/gothic_trim/metalsupport4j.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/1421E6B4AC9E76B019F3306886A9F8AE
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0022.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/spices1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/3249DD4695775E9AF4A262D79707CE51
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0023.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/spices4.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/95688CEF451207FB4F91EA50C5420356
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0024.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/spices2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/014F6497CACC730094963760F47520BB
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0024.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/spices3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/4A2BE853FD8E6688747730D35343DD57
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/bricks4_broken.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/3AC12E69979991EF7C977B88A7768141
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0013.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/kiste1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/06EA0059CE696C5588A492C86BC20512
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/kiste1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/F4E481077643442BD4C3EB0740579FEC
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/kiste1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/11FE2556DDD85752E29DFAD0E286C5E8
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.18750 0.03906
	}

	{
		map textures/shibam/kiste1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/5B54343B41FF035005EB003F10C29BF7
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/lehm2_braun.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/78F4678F9ED89500A1617CF24E758834
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/shibam/lehm6_weiss.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/FBD37C59392DE7A083A426FEA152168E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.04688 0.00000
	}

	{
		map textures/shibam/lehm6_weiss.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/787250F9119325C7FF4C2A2EECBDE976
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/lehm3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/3816DE943C9F9C1AA247BAB13BBE4638
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0017.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/lehm3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/3B4F9B7B974210F366E240C0929B8C2C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/bricks4.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/BEC55878D6432AF0D85C38C444BAAF1A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/lehm2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/4A421F60ED757B3DB9309761DBFDA86D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0017.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.09375 0.28906
	}

	{
		map textures/shibam/lehm6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/FF249F9295F70F40217D163A2B8D65C6
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0020.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/shibam/lehm6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/9521EE5EBD8F25EF8DEBC6FF24E15E70
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.68750 -0.02344
	}

	{
		map textures/shibam/lehm6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/86FE25AB979E68666DEDFAE147F8460E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/lehm6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/5CD326C683D2450B7372CEA3AC6CA1C4
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0019.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/shibam/lehm6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/3B98C00822B3BBBF727C49D3864304EF
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0019.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}

	{
		map textures/shibam/lehm6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/FF5DC5F4E9214A478C3F93F4CEAF30D5
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.29688 0.00000
	}

	{
		map textures/shibam/lehm6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/DF36917EC6E6465E97A684E39D4991C7
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.23438 0.10938
	}

	{
		map textures/shibam/lehm6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/0FD9B45DC53CC8F89149D18713E84541
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.22656 0.57031
	}

	{
		map textures/shibam/lehm6.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/6006A5A5A725C227603F2C387ABB0E2C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/holz2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/F9760748B8781602CC7A917FB091BE8A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.68750 -0.02344
	}

	{
		map textures/shibam/holz2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

shibam/75A1AD0AA033CBE52EF60B22A6F0F8B3
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/shibam/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/shibam/bricks3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

