// Custom shader file for dm2.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

dm2/C2A0FDDE8A1D85B3401E52A792C0AD64
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/ph_conc512.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/87BD00B875947ACAB7BD73F8EA373B30
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/wall309.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0006.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/90EA6AEB82DA2E919441CC0A1C30E705
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/crete02.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/6F05903565C53E1379E56B59B5411F5F
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/tile46.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/8D1CB4C701AAB8C6E1BDD1E7B59C00AB
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/metal10.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/5D4B226F25B7BCA4252C858A0139B817
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/crete02.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/17D830B0EB64E3F2F8789064C997E0A5
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/tile46.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/B3D9B373428905DA3CE659587995E5E3
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/metal10.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/D30420D00E2E6F128893E900533BB2A4
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/trim_pers183.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/272F6F7847C58C5CBE9046A098C0EFC8
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/trim_pers183red.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/17733740A2341C5825E16668CF6E3EF6
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/trim_pers183red.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/AB6D7B493DD6FA94C550F073B11B8CB2
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/plast85.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/1179BAAADD152C1EC942E3C8EA5BDEE7
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/crete02.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/9879BF95B4431782237D71696F2573C8
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/crete02.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/4004EA363612C5DFC73985924FE9E7BF
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/brix333.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/2529E5712B6BCCAC82445B3EFE5E2602
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/brix333.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0006.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/2F055970096E0F8B7D1A27539F811131
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/brix333.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/B2CCF356C1ABEDD4AD883AE5E97E223B
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/brix333.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/00590CE6EFA59F4A6D38B0FA7F6A0B38
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/brix333.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/E977F82D5AB2B05D15FD2ADCCE802614
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/c_tile01b.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/A4B3A57E45794ABF271792AABB42623E
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/c_tile01b.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/DE98CB0A14A7E813E02D86760A524516
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/c_tile01d.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/E6E89270488CC7C56470A0A8BD24BD95
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/c_tile01d.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/5604833298C71FD32CB017455DB4B270
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/c_tile01d.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0006.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/6BF936B40707F9F9DDE99A918155443B
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/c_tile01d.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/41EC6FB746E5D2D547A69AD31F85EB4A
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/col150.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/25A30F09816F5BDF0EBC56CDE3ADE96E
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/col150.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/62F1CF4E8AA5BE9DF41E6A679BAC61F4
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/col150.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0006.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/1568BDFAD97E52689082E226DB4403AC
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/col150.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/66BEEEE273ED07855BE41A2D69B74902
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/col150b.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/2160E65E381266A8FE0C424BEB01E998
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/col150b.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0006.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/414D7F21D617F1765D3838568DBFD90D
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/col150b.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/814F90ACB6BE0699AADB73DE58C53052
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/col150b.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/B88609505625FC7F5AA0EC6537FF28F6
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/col150b.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/F44173C2E1738AC8CE441696979B2067
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/col150b.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/DD9117D57887E3F5B4305563AC62AB78
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/conc005.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/D1A939B00F1DE852FE23C1E28DF5B165
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/conc005.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/35DF4313A1607582EFCDF9746A554755
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/conc005.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/5574A733D04329A24FB5A1BD8270DC80
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/conc005.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/1BC9EF8FE0D19466BD22AA0D7EFC6112
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/conc005.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/E2611CC269136513B2A65DC454B624AC
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/conc005.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0006.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/95E9077DA9C2533DE6022ECCB9D7AB05
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/crete02.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0006.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/3D1B164E10A7E93F3632A6796DD03AE3
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/crete02.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/15AE006F81FF70FC4A79D9B9AEAF4AC9
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/crete02.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/52A70B8365C15E640056DC9AF7AFBB56
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/metal10.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/96538B32D4F2D16F69FA33EB8726947D
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/metal10.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0006.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/72541AAA40179A24CBF521AC7364C8F9
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/metal10.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/CE0B316B438DAD7421F4622A55A12DD7
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/metal10.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/F8D727716997C28A5C4A35678A90E4DC
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/metal10.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/6854301C137860119E480CBDC3D466CC
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/mtrim03.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/5D64FFAA13561BD1FE0BB0E2CC4854FB
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/mtrim03.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/3B8DA3E95453DA9D19C4DA9F02B95008
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/mtrim03.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/E04514E238D6E575F7A9630B92217ADB
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/mtrim03.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/61F11E322E3F21E5BA37D39F8515C9CC
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/mtrim03.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/090FEF315592B6CEC639DA58B085DD7E
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/mtrim03.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/D06C8B358A0D16871BB0CAA744B0338D
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/mtrim03.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0006.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/48FFC8D3FD95C76CB93A485707E0AF7E
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/mtrim04.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/D0A3A6499A691E8891F6F36599F7322B
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/mtrim04.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/E2FA4423B0180EE2827623035DC033D5
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/mtrim04.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/D6CF4EFE82CA03EC54DDECE1220A30F5
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/mtrim04.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/CBAB5D992BAAC4E38C4DE7C0CE10C261
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/mtrim04.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/1F8914F959A914F2FE713ECA7410E45E
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/mtrim04.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/6303D591050A78FFB48FEE4A385DDAFC
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/mtrim04.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0006.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/A7AECEAE384CA5B74705B15002C0D1B0
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/mtrim995.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/EE3EF4B8B88E29B434A7D795EA3732D2
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/mtrim995.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/559DC13ED47ADD0C30E6CF202D053256
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/mtrim995.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/B8FF2D1A4ED8CB194A634F52F5D83A90
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/mtrim995.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/884AFD47613C5F07F36EF70E3A8739CE
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/mtrim995.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0006.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/1E9E8BFE64D15AC2AF43A70A23D463E9
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/mtrim995.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/5ADB74A1BAF3110A58AF0D5E3285C280
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/p_wind134.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/6993D095A04D0B3E59A492B1E957CFDD
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/p_wind134.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/43B03ACBFAC022831E7175BD54A35953
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/p_wind134.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/39793B0BA295E2F2CFFD568181371B60
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/p_wind188.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/59451EBB74A17C1EAA97723A9C1C04AE
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/p_wind188.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/0F66E50FE5A99043F146CFED30F64C14
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/ph_conc512.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/5ADE612EC0FD8F8B3D70C9FDA44AE65F
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/ph_conc512.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0006.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/1B6A4E5B9FFA4C6E97F069D5FD4E23F5
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/ph_conc512.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/8B0E339DB79C93C1CAF566A9A4FB2846
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/ph_conc512.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/1F1C4FAA25B6EEAA23BE8BD8E60475F4
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/ph_conc512.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/560DEA567A348E9311BF6E572D94798B
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/ph_conc512.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/DC24FEE9D06B27A7C4CB79E45927FD26
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/plast85.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/9B644CABD6815551911E93FBDA9CB742
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/plast85.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/80BD7C07C40762596EF3F2E3BA78872D
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/plast85.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/69A1310EE6A8025FD5B35187E1269653
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/plast85.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/198CA48560A99EB6C81D1EC4E08BF037
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/plast85.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0006.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/42079F81BC48A8828BB2CE9C339A2186
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/stone79.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/5A371D3174D5FB94631FA5A24B1E3B9D
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/stone79.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/895F15754E2A505C02B13C8F28C0B73C
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/stone79.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0006.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/7A3C23715B891FA73EB5B8154334C79D
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/stone79.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/F16CF9C8A076A7492E329B5A96CB8070
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/stone79.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/971984E8F3E0273BD82CE86AA24A1609
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/stone79.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/B2B44AB5EA5084F952928025B6302066
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/stone79.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/74B4B6B1D70A481A01A099D3551DA915
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/tile016.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/C0C9AB0E290F73D2EFA0CBC2748E9044
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/tile016.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/8272F68065412AEE1E1EE331BF327DB0
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/tile016.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/BC842240494B9ECD0B37ABE623952683
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/tile016.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/3848E16364E06F006C4892648D5DB65A
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/tile016.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/65D663EA84A6A1BBFF5C70B9A888FA72
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/tile46.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/6B49E748BB5D2FB061A7251E1AD3511D
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/tile46.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/11FBDA31D2FC527A54F31437483FFFAC
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/tile46.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0006.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/EAD312DE5762C87C2506FC09B2A14D6C
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/tile46.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/07C54DFF8FB5CEC0FB14A8905CDB71EB
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/tile46.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/C981328E81FA48351CA27FFED2A99A98
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/tile236.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/0FD7BB4487F9545BC591D7FCDFF02B77
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/tile236.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/BEFC24C331ECF39B817182D490C3D26F
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/tile236.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0006.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/4B9CB1F8A3124154C70BEBBDCEC539AE
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/tile236.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/5BC1D00A3782CAB13E7ED58019D42792
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/tile236.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/4B0F2EC09577F3D63182C4E0AC44CD02
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/tile236.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/6547C4E5DD07C0CFD6ED4BB898E9D1F8
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/trim_pers183.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/FF9820D93E3EDF89F32DE5EA47860167
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/trim_pers183.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/7E95C90993BBBC9863CC6314196584D6
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/trim_pers183.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/FB97C2724D0FACE3D06524D88BE50AD7
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/trim_pers183.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/EE4A33885916E923CAC1005C051B5107
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/trim_pers183.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/4AF6E12B6A5385901CF80CDB7E476283
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/trim_pers183.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0006.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/94369E2EBB9572F22947FC13205BF42D
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/trim_pers183red.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/20DC2FDB05271DD3B6B98AA023B4E4CA
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/trim_pers183red.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/591944567D2F9629193984896227884F
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/trim_pers183red.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/13483BD9E5EE8A67F7E2EA15524F00A0
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/vent103.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/8A6A75ADF033887743CE07F5C6614165
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/vent103.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/A93173873F05ED4153BCEC2B95CEC3E8
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/vent238.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/F20557DB40DEC6A251900C3F01379D8E
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/vent238.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/F1816F130A913E4FA403982A84591D77
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/wall309.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/5672C60E820DE1B2C1D652F6E9C71E3E
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/wall309.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/04074A6D1F59427EF9C26DBB1B1A286E
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/wall309.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/B3F2BF0E5E95A6A043283A62F3F4E676
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/wall309.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/2509EFEE0A319861F256CD105BEEBBE9
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/wall309.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0000.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/51A227CE2F9AB52752EE28ADD25DF7DA
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/wall309.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/9A876FCFA2BBACEA746EAAC25A814D92
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/wall718.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0005.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/49C42C96275672F4AE91862E3A924ED7
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/wall718.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0004.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/F85CBCC1DFB1F1FA1301C45207A429FA
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/wall718.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0006.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/18157E817E851B9E04D70B88D5E8DC8C
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/wall718.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0003.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/B2E1660510E51BB9932FF344FB5182A1
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/wall718.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0001.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/532BE122E21FE8BEEE9C9F9C1E82CA0A
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/wall718.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0002.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

dm2/EF1F1E7660F763D4CC40D8F000FAC487
{
	q3map_lightmapSize 2048 1024
	q3map_lightmapBrightness 1.88
	{
		map textures/dm2/zbrix084.tga
		rgbGen identity
	}
	{
		tcgen lightmap
		map maps/dm2/lm_0006.tga
		tcgen lightmap
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identityLighting
	}
}

