// Custom shader file for cpm24a_fkd_vq3.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

cpm24a_fkd_vq3/8514129166A1AFEA82E89A999F95F4EB
{
qer_editorimage textures/cpm24_fkd/pipe5.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/pipe5.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/F7B89BE9EB4EABED2AB3A909FD729E88
{
qer_editorimage textures/cpm24_fkd/Concrete_05.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/Concrete_05.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/67B6125BF44A858934D5BADEB9E11114
{
qer_editorimage textures/cpm24_fkd/trim3.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim3.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/8B16811C18326D67719BD42AD03BF35B
{
qer_editorimage textures/cpm24_fkd/wall_panels_6_b.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panels_6_b.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/E0360479587A4339BE42221EB453FD30
{
surfaceparm nonsolid
qer_editorimage textures/cpm24_fkd/pipe5.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/pipe5.tga
	blendFunc GL_DST_COLOR GL_ZERO
	rgbGen identity
}
}

cpm24a_fkd_vq3/98A352BAAA554580378AAD39CFE84335
{
qer_editorimage textures/cpm24_fkd/trim6.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim6.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/DA3964518AE5A0BF8D75AE572526E2AE
{
surfaceparm nonsolid
qer_editorimage textures/cpm24_fkd/Concrete_05.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/Concrete_05.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/254F28F77E621E555FAE3B46BA240B13
{
qer_editorimage textures/cpm24_fkd/trim6.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim6.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/71CAABC5438E08D4A477DE993A8D0B9D
{
surfaceparm nonsolid
qer_editorimage textures/cpm24_fkd/pipe5.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/pipe5.tga
	blendFunc GL_DST_COLOR GL_ZERO
	rgbGen identity
}
}

cpm24a_fkd_vq3/EA7648F585879E8676100077512CE2D8
{
surfaceparm nonsolid
qer_editorimage textures/cpm24_fkd/pipe5.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/pipe5.tga
	blendFunc GL_DST_COLOR GL_ZERO
	rgbGen identity
}
}

cpm24a_fkd_vq3/9A7B72A354FAFFBB73826831B3915E30
{
qer_editorimage textures/cpm24_fkd/trim_13_fkd3.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0003.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim_13_fkd3.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/6C98239530DD31D7126DDF105EAE8065
{
qer_editorimage textures/cpm24_fkd/wall_panels_6_b.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0003.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panels_6_b.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/24A3C8C3868071D9DFBB679B755FE097
{
qer_editorimage textures/cpm24_fkd/beam_fkd2.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/beam_fkd2.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/20147384F12FFF7147798BFA4F41E6FA
{
qer_editorimage textures/cpm24_fkd/wall_panel1_plain.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0003.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panel1_plain.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/21689D53B4E250BB307B6EBFD79F330D
{
qer_editorimage textures/cpm24_fkd/ceilgray.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/ceilgray.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/7868AF7775DC3DAA1836094ACA963A84
{
qer_editorimage textures/cpm24_fkd/trim3.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim3.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/5A12B24E728998228885CDE41507E905
{
qer_editorimage textures/cpm24_fkd/trim8_a_sharp.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim8_a_sharp.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/EBC722EF9A9E336ABC76151D675F3EBE
{
qer_editorimage textures/cpm24_fkd/wall_panels_1_a.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0003.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panels_1_a.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/B2398E052DDDAFA75BD7122E604E9840
{
surfaceparm nonsolid
qer_editorimage textures/cpm24_fkd/pipe5.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0003.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/pipe5.tga
	blendFunc GL_DST_COLOR GL_ZERO
	rgbGen identity
}
}

cpm24a_fkd_vq3/EF2F712F749F7B50EF0C3B95D4054AC5
{
qer_editorimage textures/cpm24_fkd/wall_panels_6.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panels_6.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/18B13C37F51AEBEEA33E5095DB1402A5
{
qer_editorimage textures/cpm24_fkd/phantq3dm6_bevel_smooth.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/phantq3dm6_bevel_smooth.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/D89A052BB9748E944292C7CF557FA2E5
{
qer_editorimage textures/cpm24_fkd/wall_panel1_b.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0003.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panel1_b.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/6D01FD0D78A17EC2E77E76C4100AEC81
{
qer_editorimage textures/cpm24_fkd/trim10.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim10.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/5AD6A0A975FA568546A32164C93AD7E5
{
qer_editorimage textures/cpm24_fkd/trim10.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim10.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/A295227860E9ACF0AB95414039E5A0D4
{
qer_editorimage textures/cpm24_fkd/phantq3dm6_trim_004.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/phantq3dm6_trim_004.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/63A47BDEB68AF2DAF5D39C544281F963
{
qer_editorimage textures/cpm24_fkd/phantq3dm6_trim_004.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/phantq3dm6_trim_004.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/7A2387B50E72582B1B6494D7DD8C5B0A
{
qer_editorimage textures/cpm24_fkd/pipe5.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/pipe5.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/7C9AB564B409ACCE53D47DA4567E9272
{
qer_editorimage textures/cpm24_fkd/phantq3dm6_trim_verical_001.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/phantq3dm6_trim_verical_001.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/1020F1B1E18220439CD3A80C1EBA706F
{
qer_editorimage textures/cpm24_fkd/trim3.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim3.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/65C7C95CBC3FF6AB1CE8451EDB49C385
{
qer_editorimage textures/cpm24_fkd/phantq3dm6_bevel_smooth.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/phantq3dm6_bevel_smooth.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/D5D98F2DF6AD4FFC390C1422656B2407
{
qer_editorimage textures/cpm24_fkd/trim10_a.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim10_a.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/7B1FF30BD92A9198628EFA6016E41A67
{
qer_editorimage textures/cpm24_fkd/wall_panels_6_a.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0003.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panels_6_a.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/ED0BB0209062519FC6192A8339E9465F
{
qer_editorimage textures/cpm24_fkd/phantq3dm6_trim_004.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/phantq3dm6_trim_004.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/89F122F744E3B6501CE30701E5F57982
{
qer_editorimage textures/cpm24_fkd/pipe5.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/pipe5.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/240404C570A29DA0E0F41A1B24B38355
{
qer_editorimage textures/cpm24_fkd/trim12.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim12.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/E9592B19FC280CD7479FA9852D96F0AC
{
qer_editorimage textures/cpm24_fkd/wall_panel1_b_patch.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0003.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panel1_b_patch.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/D3EE93BB0F86B6EC9630B54FD80D37D7
{
qer_editorimage textures/cpm24_fkd/floorgrate_01.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/floorgrate_01.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/4E503D7809A29F8C1EE4C01AAA983325
{
qer_editorimage textures/cpm24_fkd/phantq3dm6_trim_verical_001.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/phantq3dm6_trim_verical_001.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/B9405B159D1621DBCC4120349A0D3DB5
{
qer_editorimage textures/cpm24_fkd/trim6.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim6.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/F1B76B92C198BC49038987430AD3CA4D
{
surfaceparm nonsolid
qer_editorimage textures/cpm24_fkd/Concrete_05.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/Concrete_05.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/1FE9FBA99CB0BDE245B6DBDE67B7327E
{
qer_editorimage textures/cpm24_fkd/trim_13_fkd3.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim_13_fkd3.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/7FD2337CA7D5518C3788F79360C46115
{
qer_editorimage textures/cpm24_fkd/floor_3.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	map textures/cpm24_fkd/floor_3.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/water_ref.jpg
	blendFunc add
	tcGen environment
	rgbGen identity
	tcmod scale 2 2
}
{
	map textures/cpm24_fkd/floor_3.tga
	blendFunc blend
	rgbGen identity
}
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	blendfunc gl_dst_color gl_zero
	rgbGen identity
}
}

cpm24a_fkd_vq3/89A89F474C4BFA93E3ED202541C2D7EC
{
qer_editorimage textures/cpm24_fkd/wall_panels_6.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0003.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panels_6.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/87CEC998D95961868708F338A294826C
{
qer_editorimage textures/cpm24_fkd/wood_1.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
surfaceparm nonsolid
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wood_1.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/2F328ADB9798E7503F1C354D3083B7CB
{
qer_editorimage textures/cpm24_fkd/wood_1.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
surfaceparm nonsolid
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wood_1.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/C9226CA423454B8AE121C338FB3B626E
{
qer_editorimage textures/cpm24_fkd/wood_1.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
surfaceparm nonsolid
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0003.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wood_1.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/A7D3CD53D1D58B7D3D8065DC47B5F533
{
qer_editorimage textures/cpm24_fkd/wood_1.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
surfaceparm nonsolid
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wood_1.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/6841F5D4AD70A56756C347E74D11C177
{
qer_editorimage textures/cpm24_fkd/wood_1.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wood_1.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/7CB647BCEFEA1B7EE4FFD41DDEBF7E4A
{
qer_editorimage textures/cpm24_fkd/wood_1.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wood_1.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/51F79BAF599ACE1A76B845642AA23393
{
qer_editorimage textures/cpm24_fkd/wall_panels_5.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panels_5.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/81C99105F173E9E69E264D9B64B625D5
{
qer_editorimage textures/cpm24_fkd/wall_panels_5.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0003.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panels_5.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/C8ED54B08361B14639740679C67F5763
{
qer_editorimage textures/cpm24_fkd/trim10_end.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim10_end.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/CD80C867D226B863EDBD3D138B7D9AE6
{
qer_editorimage textures/cpm24_fkd/trim10_end.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim10_end.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/B3F5EA80508219405E3FF55CC0FDDE75
{
qer_editorimage textures/cpm24_fkd/trim10_end.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim10_end.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/3240154A2AF440B5F12A2D464C3487DE
{
qer_editorimage textures/cpm24_fkd/trim10_a.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim10_a.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/9186C0E7336E8E5F320A9B5A37AD3549
{
qer_editorimage textures/cpm24_fkd/trim10_a.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0003.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim10_a.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/B307F1B413186C339EB56358024B11B4
{
qer_editorimage textures/cpm24_fkd/trim10_a.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim10_a.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/70EA3D2E7A285A0F0BBAF27C822B3CBF
{
qer_editorimage textures/cpm24_fkd/wall_panels_1_a.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panels_1_a.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/80B07AA412661296B83CD06432577ECD
{
qer_editorimage textures/cpm24_fkd/wall_panels_1_a.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panels_1_a.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/F9DFBA36D10128572B01A38ADBDF4666
{
qer_editorimage textures/cpm24_fkd/wall_panels_1_a.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panels_1_a.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/7D2AA724451A7FF65D562479F284A85C
{
qer_editorimage textures/cpm24_fkd/ceilgray.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/ceilgray.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/6673C4EBCDA19D2847E1897EB6D1C9B9
{
qer_editorimage textures/cpm24_fkd/phantq3dm6_bevel_smooth.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/phantq3dm6_bevel_smooth.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/6ECF6BD5714646395F48B28C71E1D918
{
qer_editorimage textures/cpm24_fkd/trim10.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0003.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim10.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/6CF23A76D9045F0D483B6CB71B7FDB04
{
qer_editorimage textures/cpm24_fkd/trim10.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim10.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/842E230CFDA4F50DDC1A385ED109D582
{
qer_editorimage textures/cpm24_fkd/trim6.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0003.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim6.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/32375F3C0457BD76C5D4E9B6245F99B2
{
qer_editorimage textures/cpm24_fkd/floorgrate_01.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/floorgrate_01.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/21CC388438527AEECC707299F979916B
{
qer_editorimage textures/cpm24_fkd/floorgrate_01.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/floorgrate_01.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/5A4CA22A15C400EF77C1E8AA2B1955D8
{
qer_editorimage textures/cpm24_fkd/floor_panels_4.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/floor_panels_4.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/801F28CB2F5B44DDFA5DDC0AB877AD3B
{
qer_editorimage textures/cpm24_fkd/floor_panels_4.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/floor_panels_4.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/5D60D6B62865D3AD333AC022AFFA712B
{
qer_editorimage textures/cpm24_fkd/floor_panels_4.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/floor_panels_4.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/DC5724F1ACE7368CF4650E3EA8FEAB5A
{
qer_editorimage textures/cpm24_fkd/wall_panels_6_b.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panels_6_b.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/72163C3A25EA7BF3E9540DB564BEBF34
{
qer_editorimage textures/cpm24_fkd/wall_panels_6_b.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panels_6_b.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/1EB99D4CB799EEE017E2BD10B61C9858
{
qer_editorimage textures/cpm24_fkd/wall_panels_6_a.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panels_6_a.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/5C04AB23100DCE9B6F6C7CC5982ACFE7
{
qer_editorimage textures/cpm24_fkd/wall_panels_6_a.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panels_6_a.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/50BA1B648F9D773711927E8BC50F2252
{
qer_editorimage textures/cpm24_fkd/wall_panels_6_a.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panels_6_a.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/1D0989845C387328ED07D8EE4A5BEFE9
{
qer_editorimage textures/cpm24_fkd/wall_panels_6.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panels_6.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/293FF40857B37C014FCE60E690AB8612
{
qer_editorimage textures/cpm24_fkd/wall_panels_6.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panels_6.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/8352958CA5639761E39A9CBFAA5E4800
{
qer_editorimage textures/cpm24_fkd/wall_panel1_b.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panel1_b.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/E343EB034ED2A80E11CDC11BE72AB4D0
{
qer_editorimage textures/cpm24_fkd/wall_panel1_b.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panel1_b.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/18FDB95F02E153A6619012A62721BE62
{
qer_editorimage textures/cpm24_fkd/wall_panel1_b.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panel1_b.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/7711AE10C970C97F46EFF4C99629E6F0
{
qer_editorimage textures/cpm24_fkd/phantq3dm6_trim_verical_001.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/phantq3dm6_trim_verical_001.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/0D7BA4B7A05B946E23DD5271CDBDE3BD
{
qer_editorimage textures/cpm24_fkd/Concrete_05.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/Concrete_05.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/C0BCCFB563B9C076A3574196A73A8EAE
{
qer_editorimage textures/cpm24_fkd/conc_lowwall2_end.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/conc_lowwall2_end.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/28C515BAF125F5B20B87C339BE9159F8
{
qer_editorimage textures/cpm24_fkd/conc_lowwall2_end.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/conc_lowwall2_end.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/C93825F5B2746A0F09553F50F6110607
{
qer_editorimage textures/cpm24_fkd/conc_lowwall2.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/conc_lowwall2.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/0434421D1F3BB612AB27178B5CA78CA6
{
qer_editorimage textures/cpm24_fkd/conc_lowwall2.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/conc_lowwall2.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/72A4F5AD5614E174D7689B33470D80A9
{
qer_editorimage textures/cpm24_fkd/floor_panels_1.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/floor_panels_1.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/CB3EF865DE9A17D7E88DDBE97C40E3A7
{
qer_editorimage textures/cpm24_fkd/floor_panels_1.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/floor_panels_1.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/FFD38AED229695D5723DA99327B2D21B
{
qer_editorimage textures/cpm24_fkd/floor_panels_1.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/floor_panels_1.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/8A13C4EC1A307DD01A84E0718545C89A
{
qer_editorimage textures/cpm24_fkd/beam_fkd2.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/beam_fkd2.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/1B734CE096A5AC086B9F3E04DFFDA936
{
qer_editorimage textures/cpm24_fkd/trim3.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0003.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim3.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/194C86BB0ED6B38E8CC1B04001FBCFAF
{
qer_editorimage textures/cpm24_fkd/door.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/door.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/78089C71A62A981EE49F8F5876EFD43B
{
qer_editorimage textures/cpm24_fkd/wall_panels_4.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panels_4.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/4EEEB403EF1C72177A1D7F5F45B1AA76
{
qer_editorimage textures/cpm24_fkd/wall_panels_4.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panels_4.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/AC635AF5898C2DAC17B1DF00B0580250
{
qer_editorimage textures/cpm24_fkd/wall_panels_4.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panels_4.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/FED60EA5ABD52DFA9F07BD4E163CF143
{
qer_editorimage textures/cpm24_fkd/wall_panels_4.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0003.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panels_4.tga
	blendFunc filter
}
}

cpm24a_fkd_vq3/68F847BDCABBB0D5EF641440023B7DDF
{
qer_editorimage textures/cpm24_fkd/trim_brown2_end.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim_brown2_end.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/45930337A32500B07DC211D632EB74AA
{
qer_editorimage textures/cpm24_fkd/trim_brown2_end.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim_brown2_end.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/043F4F2B9FD9A4A4B8178235D92DCA1C
{
qer_editorimage textures/cpm24_fkd/trim_brown2_end.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0003.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim_brown2_end.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/1614CA28A67934D04F202D087E2DB007
{
qer_editorimage textures/cpm24_fkd/trim_brown2_end.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim_brown2_end.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/227F34B5136961D4B82E0BC5600A4CDC
{
qer_editorimage textures/cpm24_fkd/trim_brown2.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim_brown2.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/ADF08CD2FC346FC5730F476AB509DA11
{
qer_editorimage textures/cpm24_fkd/trim_brown2.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim_brown2.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/81AF52BCE47ACCFD748A7578CC7069C4
{
qer_editorimage textures/cpm24_fkd/trim_brown2.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0003.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim_brown2.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/524C2D7CF205819918956130C6AC6259
{
qer_editorimage textures/cpm24_fkd/trim_brown2.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim_brown2.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/9D960463F5AA59765D0629DDA2BFF25A
{
qer_editorimage textures/cpm24_fkd/trim_13_fkd3.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim_13_fkd3.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/83223C1851D06CA1CD81D5F31917FA9A
{
qer_editorimage textures/cpm24_fkd/trim_13_fkd3.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim_13_fkd3.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/0EF120B947CEF7BDE05BC71F907D5E84
{
qer_editorimage textures/cpm24_fkd/wall_panel1_b_patch.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panel1_b_patch.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/E8757834536A8ECF39A9256127BE9687
{
qer_editorimage textures/cpm24_fkd/wall_panel1_plain.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panel1_plain.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/F769092A40AA321F6A9B5C16D4651A5F
{
qer_editorimage textures/cpm24_fkd/wall_panel1_plain.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/wall_panel1_plain.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/134BC0F0B975235285962875B03E3403
{
qer_editorimage textures/cpm24_fkd/floorgrate_01_angle.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/floorgrate_01_angle.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/D166E6427117D1902DAEA79DEFA5FA44
{
qer_editorimage textures/cpm24_fkd/floorgrate_01_angle.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/floorgrate_01_angle.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/103A659761A91123FC5A686D38B9CCC4
{
qer_editorimage textures/cpm24_fkd/trim8_a_sharp.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim8_a_sharp.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/516CAB5C43131D61D493DA2BAB193D93
{
qer_editorimage textures/cpm24_fkd/trim8_a_sharp.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim8_a_sharp.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/9C53DFB2B2306AD31204B9F8BCF46E54
{
qer_editorimage textures/cpm24_fkd/trim8_a_sharp.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0003.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim8_a_sharp.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/00940B834F2C0A0EB822A48A1067C6AC
{
qer_editorimage textures/cpm24_fkd/trim12.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim12.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/A3C0AFEBC25D34683B25DB4047BB0893
{
qer_editorimage textures/cpm24_fkd/trim12.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim12.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/A58E579097685372CE9877A2769F5431
{
qer_editorimage textures/cpm24_fkd/trim8_sharp.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim8_sharp.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/DF50D77014339934E0F2B53B4C52B4C4
{
qer_editorimage textures/cpm24_fkd/trim8_sharp.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim8_sharp.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/23F63CB2B332AC53CD776B1C8A63C851
{
qer_editorimage textures/cpm24_fkd/trim8_sharp.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim8_sharp.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/B5603C055B4F7EE3AE4CA7EF26B9B314
{
qer_editorimage textures/cpm24_fkd/trim8_sharp.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0003.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/trim8_sharp.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/00E3DC8C7F1AE1765DFD703D01B74569
{
qer_editorimage textures/cpm24_fkd/tab_crate_1.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/tab_crate_1.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/5DEB987DB92CB4F2FF4449C0DB813806
{
qer_editorimage textures/cpm24_fkd/tab_crate_1_top.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/tab_crate_1_top.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/FF2083E298F3C8196C6AC0A41F1DDB90
{
qer_editorimage textures/cpm24_fkd/tab_crate_1_top.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/tab_crate_1_top.jpg
	blendFunc filter
}
}

cpm24a_fkd_vq3/9F1117FA9A00B78199B27EAA06434B72
{
qer_editorimage textures/cpm24_fkd/floor_3.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	map textures/cpm24_fkd/floor_3.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/water_ref.jpg
	blendFunc add
	tcGen environment
	rgbGen identity
	tcmod scale 2 2
}
{
	map textures/cpm24_fkd/floor_3.tga
	blendFunc blend
	rgbGen identity
}
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	blendfunc gl_dst_color gl_zero
	rgbGen identity
}
}

cpm24a_fkd_vq3/886ECC7D0ACCA85936002C6D44A02C28
{
qer_editorimage textures/cpm24_fkd/floor_3.tga
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	map textures/cpm24_fkd/floor_3.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/water_ref.jpg
	blendFunc add
	tcGen environment
	rgbGen identity
	tcmod scale 2 2
}
{
	map textures/cpm24_fkd/floor_3.tga
	blendFunc blend
	rgbGen identity
}
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	blendfunc gl_dst_color gl_zero
	rgbGen identity
}
}

cpm24a_fkd_vq3/7B99A1F916FB25E413C234430646407D
{
q3map_nonplanar
qer_editorimage textures/cpm24_fkd/floor_treadplate_03.tga
surfaceparm metalsteps
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0001.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/floor_treadplate_03.tga
	blendFunc GL_DST_COLOR GL_ZERO
	rgbGen identity
}
}

cpm24a_fkd_vq3/02291A6538196BDB2C2C3F8059756438
{
q3map_nonplanar
qer_editorimage textures/cpm24_fkd/floor_treadplate_03.tga
surfaceparm metalsteps
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0002.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/floor_treadplate_03.tga
	blendFunc GL_DST_COLOR GL_ZERO
	rgbGen identity
}
}

cpm24a_fkd_vq3/5BDA9548861212B32E6A1955410449A8
{
surfaceparm nonsolid
qer_editorimage textures/cpm24_fkd/floor_panels_4.jpg
q3map_lightmapSize 2048 1024
q3map_lightmapBrightness 2
{
	tcgen lightmap
	map maps/cpm24a_fkd_vq3/lm_0000.tga
	rgbGen identity
}
{
	map textures/cpm24_fkd/floor_panels_4.jpg
	blendFunc filter
}
}

